[package]
name = "device-envoy-esp-demos"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = []
esp32 = [
    "device-envoy-esp/esp32",
    "esp-hal/esp32",
    "esp-rtos/esp32",
    "esp-backtrace/esp32",
    "esp-println/esp32",
    "esp-bootloader-esp-idf/esp32",
]
esp32c2 = [
    "device-envoy-esp/esp32c2",
    "esp-hal/esp32c2",
    "esp-rtos/esp32c2",
    "esp-backtrace/esp32c2",
    "esp-println/esp32c2",
    "esp-bootloader-esp-idf/esp32c2",
]
esp32c3 = [
    "device-envoy-esp/esp32c3",
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
]
esp32c6 = [
    "device-envoy-esp/esp32c6",
    "esp-hal/esp32c6",
    "esp-rtos/esp32c6",
    "esp-backtrace/esp32c6",
    "esp-println/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
]
esp32h2 = [
    "device-envoy-esp/esp32h2",
    "esp-hal/esp32h2",
    "esp-rtos/esp32h2",
    "esp-backtrace/esp32h2",
    "esp-println/esp32h2",
    "esp-bootloader-esp-idf/esp32h2",
]
esp32s2 = [
    "device-envoy-esp/esp32s2",
    "esp-hal/esp32s2",
    "esp-rtos/esp32s2",
    "esp-backtrace/esp32s2",
    "esp-println/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
]
esp32s3 = [
    "device-envoy-esp/esp32s3",
    "esp-hal/esp32s3",
    "esp-rtos/esp32s3",
    "esp-backtrace/esp32s3",
    "esp-println/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
]

[dependencies]
device-envoy-esp = { path = "..", default-features = false }
embassy-executor = { version = "0.9.0" }
embassy-time = { version = "0.5.0" }
smart-leds = { version = "0.4.0" }
embedded-graphics = { version = "0.8.1" }
heapless = { version = "0.8.0" }
paste = { version = "1.0" }
static_cell = { version = "2.1.0" }

[target.'cfg(target_os = "none")'.dependencies]
esp-hal = { version = "1.0.0", features = ["unstable"] }
esp-rtos = { version = "0.2.0", features = ["embassy", "esp-radio", "esp-alloc"] }
esp-backtrace = { version = "0.18.1", features = [
    "panic-handler",
    "halt-cores",
    "println",
] }
esp-println = { version = "0.16.1", default-features = false, features = ["uart", "log-04"] }
esp-bootloader-esp-idf = { version = "0.4.0" }
embassy-net = { version = "0.8.0", features = ["dhcpv4", "dns", "proto-ipv4", "udp", "tcp"] }

[[bin]]
name = "demo_a1_strip_8_blue_gray"
path = "a_strip/a1_strip_8_blue_gray.rs"
test = false

[[bin]]
name = "demo_a3_strip_8_blue_white_blink_animate"
path = "a_strip/a3_strip_8_blue_white_blink_animate.rs"
test = false

[[bin]]
name = "demo_a4_strip_96_blue_white_dot"
path = "a_strip/a4_strip_96_blue_white_dot.rs"
test = false

[[bin]]
name = "demo_b1_panel_12x8_rust_cursor"
path = "b_panel/b1_panel_12x8_rust_cursor.rs"
test = false

[[bin]]
name = "demo_b2_panel_12x8_text_graphics"
path = "b_panel/b2_panel_12x8_text_graphics.rs"
test = false

[[bin]]
name = "demo_f1_dns"
path = "f_wifi_auto/f1_dns.rs"
test = false
