[package]
name = "device-envoy-dns-tester-wasm"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
device-envoy-core = { path = "../device-envoy-core", features = ["wasm"] }
embedded-graphics = { version = "0.8", default-features = false }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "CanvasRenderingContext2d",
    "Document",
    "HtmlCanvasElement",
    "Window",
] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
