/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const _embassy_time_now: () => bigint;
export const start: (a: number, b: number) => [number, number, number];
export const __wbg_cydsimulatorcontrolwasm_free: (a: number, b: number) => void;
export const __wbg_cydwebapphandle_free: (a: number, b: number) => void;
export const __wbg_cydwebnotice_free: (a: number, b: number) => void;
export const cydsimulatorcontrolwasm_boot_down: (a: number) => void;
export const cydsimulatorcontrolwasm_boot_up: (a: number) => void;
export const cydsimulatorcontrolwasm_orientation_is_inverted: (a: number) => number;
export const cydsimulatorcontrolwasm_reset_transient_state: (a: number) => void;
export const cydsimulatorcontrolwasm_touch_down: (a: number, b: number, c: number) => void;
export const cydsimulatorcontrolwasm_touch_move: (a: number, b: number, c: number) => void;
export const cydsimulatorcontrolwasm_touch_up: (a: number) => void;
export const cydwebapphandle_boot_down: (a: number) => void;
export const cydwebapphandle_boot_up: (a: number) => void;
export const cydwebapphandle_clear_storage_and_restart: (a: number) => void;
export const cydwebapphandle_clock_control_is_visible: (a: number) => number;
export const cydwebapphandle_orientation_is_inverted: (a: number) => number;
export const cydwebapphandle_page_controls: (a: number) => [number, number];
export const cydwebapphandle_page_core_code_url: (a: number) => [number, number];
export const cydwebapphandle_page_description: (a: number) => [number, number];
export const cydwebapphandle_page_preview: (a: number) => [number, number];
export const cydwebapphandle_page_title: (a: number) => [number, number];
export const cydwebapphandle_request_restart: (a: number) => void;
export const cydwebapphandle_set_clock_time_of_day: (a: number, b: number) => [number, number];
export const cydwebapphandle_take_notice: (a: number) => number;
export const cydwebapphandle_touch_down: (a: number, b: number, c: number) => void;
export const cydwebapphandle_touch_move: (a: number, b: number, c: number) => void;
export const cydwebapphandle_touch_up: (a: number) => void;
export const cydwebapphandle_use_live_clock: (a: number) => void;
export const cydwebnotice_detail: (a: number) => [number, number];
export const cydwebnotice_id: (a: number) => [number, number];
export const cydwebnotice_severity: (a: number) => number;
export const _embassy_time_schedule_wake: (a: bigint, b: number) => void;
export const wasm_bindgen_c4636c65afc58f47___convert__closures_____invoke___f64______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_c4636c65afc58f47___convert__closures_____invoke___wasm_bindgen_c4636c65afc58f47___JsValue__core_7d5f0a2ba6a62c33___result__Result_____wasm_bindgen_c4636c65afc58f47___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c4636c65afc58f47___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
