[workspace]
resolver = "2"
members = [
    "xtask",
    "crates/device-envoy",
    "crates/device-envoy-conway-wasm",
    "crates/device-envoy-dns-tester-wasm",
    "crates/device-envoy-core",
    "crates/device-envoy-examples-core",
    "crates/device-envoy-example-common",
    "crates/device-envoy-rp",
    "crates/device-envoy-rp/demos",
    "crates/device-envoy-rp/tests-compile-only",
    "crates/device-envoy-rp/xtask",
    "crates/device-envoy-esp",
    "crates/device-envoy-esp/xtask",
]

[profile.dev]
panic = "abort"

[profile.dev.package.esp-radio]
opt-level = 3

[profile.release]
# debug = 2    # uncomment for better backtraces, at the cost of code size
lto = "thin"
codegen-units = 1
panic = "abort"
