// @generated by cargo xtask generate-board-examples
//! SunFounder Kepler IR remote demo.
//!
//! Wiring:
//! - IR receiver data output -> GPIO7
//! - IR receiver VCC -> 3.3V
//! - IR receiver GND -> GND

#![no_std]
#![no_main]

use core::convert::Infallible;
use embassy_executor::Spawner;
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start, ir::IrKepler as _, ir_kepler};

esp_bootloader_esp_idf::esp_app_desc!();

ir_kepler! {
    IrKeplerBoard { pin: GPIO7 }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Async);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let channel_creator = rmt80.channel2;
    let ir_kepler_board = IrKeplerBoard::new(p.GPIO7, channel_creator, spawner)?;

    loop {
        let button = ir_kepler_board.wait_for_press().await;
        info!("Kepler button: {:?}", button);
    }
}
