// @generated by `cargo check-all`. Do not edit by hand.
//! Module containing [`LcdTextGenerated`], the sample struct type generated by
//! the [`lcd_text!`](macro@crate::lcd_text) macro.
//!
//! Auto-generated.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::lcd_text;

#[cfg(all(not(doc), not(feature = "host")))]
lcd_text! {
    pub LcdTextGenerated {
        width: 16,
        height: 2,
        i2c: I2C0,
        sda_pin: PIN_4,
        scl_pin: PIN_5,
    }
}

#[cfg(doc)]
/// Sample struct type generated by the [`lcd_text!`](macro@crate::lcd_text) macro.
///
/// This page exists to show constructor and methods in one place.
/// For narrative examples, see the [`lcd_text`](mod@crate::lcd_text) module.
///
/// Auto-generated.
pub struct LcdTextGenerated;

#[cfg(doc)]
use crate::Result;

#[cfg(doc)]
impl LcdTextGenerated {
    /// Display width in characters.
    pub const WIDTH: usize = 16;
    /// Display height in characters.
    pub const HEIGHT: usize = 2;

    /// Create a new LCD text instance of the struct type defined by
    /// [`lcd_text!`](macro@crate::lcd_text).
    ///
    /// See the [`lcd_text`](mod@crate::lcd_text) module docs for usage examples.
    pub fn new(
        i2c_peripheral: embassy_rp::Peri<'static, embassy_rp::peripherals::I2C0>,
        sda: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_4>,
        scl: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_5>,
        address: u8,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: LcdTextGenerated = LcdTextGenerated;
        let _ = (i2c_peripheral, sda, scl, address, spawner);
        Ok(&INSTANCE)
    }

    /// Write text to the display using clamp-to-frame behavior.
    pub fn write_text(&self, text: impl AsRef<str>) {
        let _ = text;
    }
}
