// @generated by cargo xtask generate-board-examples
//! Talk 1 demo: 12x8 panel text ("Go\\nGo") with cursor-like layout.
//!
//! Wiring:
//! - NeoPixel-style (WS2812) panel data input -> GPIO2
//! - Panel power -> 5V (or per panel spec), shared GND with board

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending, panic};

use device_envoy_esp::{
    Result, init_and_start,
    led_strip::colors,
    led2d,
    led2d::Led2d as _,
    led2d::{Led2dFont, layout::LedLayout},
};
use embassy_executor::Spawner;
use esp_backtrace as _;

// Two 12x4 panels stacked vertically to create a 12x8 display.
const LED_LAYOUT_12X4: LedLayout<48, 12, 4> = LedLayout::serpentine_column_major();
const LED_LAYOUT_12X8: LedLayout<96, 12, 8> = LED_LAYOUT_12X4.combine_v(LED_LAYOUT_12X4);
const LED_LAYOUT_12X8_ROTATED: LedLayout<96, 8, 12> = LED_LAYOUT_12X8.rotate_cw();

led2d! {
    Led12x8 {
        pin: GPIO2,
        len: 96,
        led_layout: LED_LAYOUT_12X8_ROTATED,
        // Use a 4x6 pixel font with no gap between characters
        font: Led2dFont::Font4x6Trim,
    }
}

esp_bootloader_esp_idf::esp_app_desc!();

// Nice trick: Two "mains" lets us use Results.
#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Blocking);
    let led12x8 = Led12x8::new(p.GPIO2, rmt80.channel0, spawner)?;

    // Text supports "\n" for multiple lines.
    // Colors are per-character, repeat as needed, and default to white.
    led12x8.write_text(
        "Go\nGo",
        &[
            colors::LIGHT_GRAY,
            colors::LIGHT_GRAY,
            colors::ORANGE,
            colors::HOT_PINK,
        ],
    );

    pending().await // run forever
}
