// @generated by cargo xtask generate-board-examples
// TODO0000 At a later date, verify that this ESP template remains in sync with
// TODO0000 the RP audio_playlist example.
//! One fixed playlist per button press.
//!
//! Wiring:
//! - Audio data pin (`DIN`) -> GPIO5
//! - Audio bit clock pin (`BCLK`) -> GPIO3
//! - Audio word select pin (`LRC` / `LRCLK`) -> GPIO4
//! - Button -> GPIO6 to GND
#![no_std]
#![no_main]

use core::convert::Infallible;
use core::time::Duration as StdDuration;

use device_envoy_core::{
    audio_player::{AtEnd, AudioPlayer as _, Gain, Playable, SilenceClip, VOICE_22050_HZ},
    button::Button as _,
};
use device_envoy_esp::{
    audio_player::{audio_player, pcm_clip},
    button::{ButtonEsp, PressedTo},
    tone,
};

use embassy_executor::Spawner;
use esp_backtrace as _;

use device_envoy_esp::{Result, init_and_start};

esp_bootloader_esp_idf::esp_app_desc!();

audio_player! {
    AudioPlayerBoard {
        data_pin: GPIO5,
        bit_clock_pin: GPIO3,
        word_select_pin: GPIO4,
        sample_rate_hz: VOICE_22050_HZ,
        dma: DMA_CH0,
        max_clips: 8,
    }
}

pcm_clip! {
    Nasa {
        file: concat!(env!("CARGO_MANIFEST_DIR"), "/examples/data/audio/nasa_22k.s16"),
        source_sample_rate_hz: VOICE_22050_HZ,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    const fn ms(milliseconds: u64) -> StdDuration {
        StdDuration::from_millis(milliseconds)
    }

    type PlayableRef = &'static dyn Playable<VOICE_22050_HZ>;
    const NASA: PlayableRef = &Nasa::adpcm_clip();
    const GAP: PlayableRef = &SilenceClip::new(ms(80));
    const CHIME: PlayableRef = &tone!(880, VOICE_22050_HZ, ms(100)).with_gain(Gain::percent(20));

    init_and_start!(p);
    let mut button = ButtonEsp::new(p.GPIO6, PressedTo::Ground);
    let audio_player_board =
        AudioPlayerBoard::new(p.GPIO5, p.GPIO3, p.GPIO4, p.I2S0, p.DMA_CH0, spawner)?;

    loop {
        button.wait_for_press().await;
        audio_player_board.play([CHIME, NASA, GAP], AtEnd::Stop);
        audio_player_board.wait_until_stopped().await;
    }
}
