// @generated by cargo xtask generate-board-examples
//! Draws a tiled, labeled grid across the full 320x240 CYD panel using a
//! small, tile-sized draw buffer rather than a full-screen one.
//!
//! Wiring: the classic CYD board's built-in ILI9341 display, fixed at the
//! factory (see `device_envoy_esp::cyd` module docs for the CYD abstraction):
//!
//! - Display SPI SCK  -> GPIO14
//! - Display SPI MOSI -> GPIO13
//! - Display SPI MISO -> GPIO12
//! - Display CS       -> GPIO15
//! - Display DC       -> GPIO2
//! - Display RST      -> GPIO4
//! - Display backlight -> GPIO21
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::{convert::Infallible, fmt::Write};

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use embedded_graphics::{
    geometry::{Point, Size},
    pixelcolor::{Rgb565, Rgb888},
};
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{
    Result,
    cyd::{
        CydDisplay as _, CydDisplayEsp, CydEsp, CydStaticEsp, DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT,
        Orientation, tiling::TileGrid,
    },
    init_and_start,
};

esp_bootloader_esp_idf::esp_app_desc!();

const TILE_COLUMNS: usize = 4;
const TILE_ROWS: usize = 4;
const TILE_WIDTH: usize = 320 / TILE_COLUMNS;
const TILE_HEIGHT: usize = 240 / TILE_ROWS;
const TILE_PIXEL_COUNT: usize = TILE_WIDTH * TILE_HEIGHT;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(_spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD tiles demo");

    static CYD_STATIC: CydStaticEsp<TILE_PIXEL_COUNT> = CydEsp::new_static();
    let mut display = CydDisplayEsp::new(
        &CYD_STATIC,
        p.SPI2,
        p.GPIO14,
        p.GPIO13,
        p.GPIO12,
        p.GPIO15,
        p.GPIO2,
        p.GPIO4,
        p.GPIO21,
        DEFAULT_DISPLAY_SPI_HZ,
        Orientation::Landscape,
        Rgb888::new(10, 10, 12),
        Rgb888::new(230, 230, 230),
        &DEFAULT_FONT,
    )?;
    info!("CYD display initialized");

    let palette = [Rgb565::new(6, 20, 10), Rgb565::new(2, 10, 25)];

    let grid = TileGrid::new(Point::zero(), Size::new(320, 240), TILE_COLUMNS, TILE_ROWS);

    loop {
        let mut tiles = display.tiles(grid);
        let mut tile_index: usize = 0;
        while let Some(mut frame) = tiles.next() {
            frame.fill(palette[tile_index % palette.len()]);
            let mut label = heapless::String::<8>::new();
            assert!(
                write!(label, "{tile_index}").is_ok(),
                "tile index label exceeds buffer"
            );
            frame.write_text(label.as_str());
            frame.flush()?;
            tile_index += 1;
        }
        Timer::after(Duration::from_secs(1)).await;
    }
}
