// @generated by cargo xtask generate-board-examples
//! Touch-triggered Wi-Fi/DNS reliability tester.
//!
//! Tap anywhere on the panel to fire one DNS query and update a running tally
//! of hits/misses and the last round-trip latency on a single status line.
//! Meant to run for hours unattended on hardware with no reachable physical
//! reset button, repeatedly exercising the touch driver and the Wi-Fi stack
//! together so long-run failures (socket exhaustion, dropped connections,
//! stuck touch reads) show up on screen instead of silently wedging the
//! board. The status line stays deliberately small: a full-screen frame
//! buffer plus the Wi-Fi stack's own heap overflows plain ESP32's DRAM.
//!
//! Wiring: the classic CYD board's built-in ILI9341 display and XPT2046
//! touch controller, fixed at the factory (see `device_envoy_esp::cyd`
//! module docs for the CYD abstraction):
//!
//! - Display/touch SPI SCK  -> GPIO14
//! - Display SPI MOSI -> GPIO13
//! - Display SPI MISO -> GPIO12
//! - Display CS       -> GPIO15
//! - Display DC       -> GPIO2
//! - Display RST      -> board reset / EN (no dedicated GPIO)
//! - Display backlight -> GPIO21
//! - Touch SPI SCK    -> GPIO25
//! - Touch SPI MOSI   -> GPIO32
//! - Touch SPI MISO   -> GPIO39
//! - Touch CS         -> GPIO33
//! - Touch IRQ        -> GPIO36
//! - Button (Wi-Fi reset while connecting; calibration backup afterward) -> GPIO0
//!   to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use derive_more::From;
use embassy_executor::Spawner;
use embedded_graphics::pixelcolor::Rgb888;
use esp_backtrace as _;
use esp_hal::system::software_reset;
use log::info;

use device_envoy_core::cyd::display::Orientation;
use device_envoy_core::dns::DnsWithStack;
use device_envoy_core::flash_block::FlashBlock as _;
use device_envoy_esp::{
    Error as DeviceEnvoyError,
    button::PressedTo,
    button_watch,
    cyd::{
        CydEsp, CydStaticEsp, DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT, Error as CydError,
        NoDisplayReset,
    },
    flash_block::FlashBlockEsp,
    init_and_start,
    wifi_auto::{WifiAuto as _, WifiAutoEsp},
};
use device_envoy_examples_core::dns_tester::{
    self as dns_tester, Error as CoreError, Exit as CoreExit,
};

esp_bootloader_esp_idf::esp_app_desc!();

button_watch! {
    ButtonWatch {
        pin: GPIO0,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    match inner_main(spawner).await {
        Ok(never) => match never {},
        Err(Error::Platform(error)) => panic!("{error:?}"),
        Err(Error::WifiStatus(error)) => panic!("{error:?}"),
        Err(Error::DnsTester(error)) => panic!("{error:?}"),
    }
}

async fn inner_main(spawner: Spawner) -> core::result::Result<Infallible, Error> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD DNS tester on ESP32 / generic");
    // configuration or are required by the compile-time display storage.
    let [
        wifi_auto_flash_block,
        mut calibration_flash_block,
        mut orientation_flash_block,
    ] = FlashBlockEsp::new_array::<3>(p.FLASH)?;
    let orientation = orientation_flash_block
        .load::<Orientation>()?
        .unwrap_or(Orientation::Landscape);

    static CYD_STATIC: CydStaticEsp<{ dns_tester::FRAME_PIXEL_COUNT }> = CydEsp::new_static();
    let button_watch = ButtonWatch::new(p.GPIO0, PressedTo::Ground, spawner).await?;

    let mut cyd = CydEsp::new(
        &CYD_STATIC,                // statics
        p.SPI2,                     // display_spi
        p.GPIO14,                   // display_sck_pin
        p.GPIO13,                   // display_mosi_pin
        p.GPIO12,                   // display_miso_pin
        p.GPIO15,                   // display_cs_pin
        p.GPIO2,                    // display_dc_pin
        NoDisplayReset,             // display_rst_pin
        p.GPIO21,                   // display_backlight_pin
        DEFAULT_DISPLAY_SPI_HZ,     // display_spi_hz
        orientation,                // orientation
        Rgb888::new(10, 10, 12),    // background: near-black
        Rgb888::new(230, 230, 230), // foreground: near-white
        &DEFAULT_FONT,              // font
        p.SPI3,                     // touch_spi
        p.GPIO25,                   // touch_sck_pin
        p.GPIO32,                   // touch_mosi_pin
        p.GPIO39,                   // touch_miso_pin
        p.GPIO33,                   // touch_cs_pin
        p.GPIO36,                   // touch_irq_pin
        &mut calibration_flash_block,
        &mut *button_watch,
    )
    .await?;

    info!("CYD display and touch initialized and calibrated");
    dns_tester::splash(&mut cyd).await?;

    let wifi_auto = WifiAutoEsp::new(p.WIFI, wifi_auto_flash_block, "DnsTesterSetup", [], spawner)?;

    let stack = wifi_auto
        .connect(
            &mut *button_watch,
            async |wifi_auto_event| -> core::result::Result<(), Error> {
                dns_tester::wifi_status(&mut cyd, wifi_auto_event).await?;
                info!("Wi-Fi: {wifi_auto_event:?}");
                Ok(())
            },
        )
        .await?;

    info!("Wi-Fi up with DHCP: {:?}", stack.config_v4());

    let mut dns = DnsWithStack::new(*stack);
    match dns_tester::run(&mut cyd, &mut *button_watch, &mut dns).await? {
        CoreExit::Calibrate => {
            calibration_flash_block.clear()?;
        }
        CoreExit::ResetWifi => {
            wifi_auto.reset_to_captive_portal()?;
        }
        CoreExit::Reorientate(next_orientation) => {
            orientation_flash_block.save(&next_orientation)?;
        }
    }
    software_reset();
}

#[derive(Debug, From)]
enum Error {
    Platform(DeviceEnvoyError),
    WifiStatus(CoreError<CydError, Infallible>),
    DnsTester(CoreError<CydError, embassy_net::dns::Error>),
}
