// @generated by cargo xtask generate-board-examples
//! Touch-triggered Wi-Fi/DNS reliability tester.
//!
//! Tap anywhere on the panel to fire one DNS query and update a running tally
//! of hits/misses and the last round-trip latency on a single status line.
//! Meant to run for hours unattended on hardware with no reachable physical
//! reset button, repeatedly exercising the touch driver and the Wi-Fi stack
//! together so long-run failures (socket exhaustion, dropped connections,
//! stuck touch reads) show up on screen instead of silently wedging the
//! board. The status line stays deliberately small: a full-screen frame
//! buffer plus the Wi-Fi stack's own heap overflows plain ESP32's DRAM.
//!
//! Wiring: the classic CYD board's built-in ILI9341 display and XPT2046
//! touch controller, fixed at the factory (see `device_envoy_esp::cyd`
//! module docs for the CYD abstraction):
//!
//! - Display SPI SCK  -> GPIO14
//! - Display SPI MOSI -> GPIO13
//! - Display SPI MISO -> GPIO12
//! - Display CS       -> GPIO15
//! - Display DC       -> GPIO2
//! - Display RST      -> GPIO4
//! - Display backlight -> GPIO21
//! - Touch SPI SCK    -> GPIO25
//! - Touch SPI MOSI   -> GPIO32
//! - Touch SPI MISO   -> GPIO39
//! - Touch CS         -> GPIO33
//! - Touch IRQ        -> GPIO36
//! - Button (Wi-Fi reset while connecting; calibration backup afterward) -> GPIO0
//!   to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;
use embassy_net::dns::DnsQueryType;
use embassy_time::Instant;
use embedded_graphics::pixelcolor::Rgb888;
use esp_backtrace as _;
use log::{info, warn};

use device_envoy_core::cyd::touch::calibration::CALIBRATION_MIN_PIXEL_COUNT;
use device_envoy_core::cyd::{Cyd as _, CydUncalibrated as _, display::Orientation};
use device_envoy_core::dns::{DnsResult, DnsRuntime};
use device_envoy_core::flash_block::FlashBlock as _;
use device_envoy_esp::{
    Error, Result,
    button::{Button as _, PressedTo},
    button_watch,
    cyd::{
        CydError, CydEsp, CydEspUncalibrated, CydStaticEsp, DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT,
    },
    flash_block::FlashBlockEsp,
    init_and_start,
    wifi_auto::{WifiAuto as _, WifiAutoEsp, WifiAutoEvent},
};
use device_envoy_examples_core::dns_tester::{
    Error as CoreError, dns_tester, dns_tester_splash, dns_tester_wifi_status, render_notice,
};

esp_bootloader_esp_idf::esp_app_desc!();

button_watch! {
    ButtonWatch {
        pin: GPIO0,
    }
}

const DNS_HOSTNAME: &str = "example.com";
const CAPTIVE_PORTAL_SSID: &str = "DeviceEnvoySetup";
/// `ensure_calibration`'s own on-screen text banner needs a buffer at least
/// `CALIBRATION_MIN_PIXEL_COUNT` pixels; its crosshair/dot geometry streams
/// buffer-free. The DNS status line uses the same small-buffer budget.
const STATUS_PIXEL_COUNT: usize = CALIBRATION_MIN_PIXEL_COUNT;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD DNS tester on ESP32 / generic");

    let [
        wifi_auto_flash_block,
        mut calibration_flash_block,
        mut orientation_flash_block,
    ] = FlashBlockEsp::new_array::<3>(p.FLASH)?;
    let orientation = orientation_flash_block
        .load::<Orientation>()?
        .unwrap_or(Orientation::Landscape);

    static CYD_STATIC: CydStaticEsp<STATUS_PIXEL_COUNT> = CydEsp::new_static();
    let uncalibrated_cyd = CydEspUncalibrated::new(
        &CYD_STATIC,                // statics
        p.SPI2,                     // display_spi
        p.GPIO14,                   // display_sck_pin
        p.GPIO13,                   // display_mosi_pin
        p.GPIO12,                   // display_miso_pin
        p.GPIO15,                   // display_cs_pin
        p.GPIO2,                    // display_dc_pin
        p.GPIO4,                    // display_rst_pin
        p.GPIO21,                   // display_backlight_pin
        DEFAULT_DISPLAY_SPI_HZ,     // display_spi_hz
        orientation,                // orientation
        Rgb888::new(10, 10, 12),    // background: near-black
        Rgb888::new(230, 230, 230), // foreground: near-white
        &DEFAULT_FONT,              // font
        p.SPI3,                     // touch_spi
        p.GPIO25,                   // touch_sck_pin
        p.GPIO32,                   // touch_mosi_pin
        p.GPIO39,                   // touch_miso_pin
        p.GPIO33,                   // touch_cs_pin
        p.GPIO36,                   // touch_irq_pin
    )?;
    let button = ButtonWatch::new(p.GPIO0, PressedTo::Ground, spawner).await?;
    let mut cyd = uncalibrated_cyd
        .into_calibrated(&mut calibration_flash_block, &mut *button)
        .await?;
    info!("CYD display and touch initialized and calibrated");
    dns_tester_splash(&mut cyd)
        .await
        .map_err(map_dns_tester_error)?;

    let wifi_auto = WifiAutoEsp::new(
        p.WIFI,
        wifi_auto_flash_block,
        CAPTIVE_PORTAL_SSID,
        [],
        spawner,
    )?;
    let stack = wifi_auto
        .connect(&mut *button, async |wifi_auto_event| -> Result<(), Error> {
            dns_tester_wifi_status(&mut cyd, wifi_auto_event)
                .await
                .map_err(map_dns_tester_error)?;
            info!("Wi-Fi: {wifi_auto_event:?}");
            Ok(())
        })
        .await?;

    info!("Wi-Fi up with DHCP: {:?}", stack.config_v4());

    // todo000 is this nice?
    let mut dns = DnsRuntime::new(DNS_HOSTNAME, async || {
        let query_start = Instant::now();
        let dns_result = stack.dns_query(DNS_HOSTNAME, DnsQueryType::A).await;
        let latency_millis = query_start.elapsed().as_millis();
        let succeeded = match dns_result {
            Ok(addresses) if !addresses.is_empty() => {
                info!("DNS ok in {latency_millis}ms: {:?}", addresses.first());
                true
            }
            Ok(_) => {
                warn!("DNS query returned no addresses");
                false
            }
            Err(_) => {
                warn!("DNS query failed");
                false
            }
        };
        Ok::<DnsResult, Infallible>(DnsResult {
            succeeded,
            latency_millis,
        })
    });
    let exit = dns_tester(&mut cyd, &mut *button, &mut dns)
        .await
        .map_err(map_dns_tester_error)?;
    match exit {
        device_envoy_examples_core::dns_tester::Exit::Calibrate => {
            calibration_flash_block.clear()?;
        }
        device_envoy_examples_core::dns_tester::Exit::ResetWifi => {
            wifi_auto.reset_to_captive_portal()?;
        }
        device_envoy_examples_core::dns_tester::Exit::Reorientate(next_orientation) => {
            orientation_flash_block.save(&next_orientation)?;
        }
    }
    device_envoy_esp::esp_hal::system::software_reset();
}

fn map_ui_error(error: device_envoy_examples_core::dns_tester::UiError<CydError>) -> Error {
    match error {
        device_envoy_examples_core::dns_tester::UiError::Text(_) => Error::FormatError,
        device_envoy_examples_core::dns_tester::UiError::Display(error) => error.into(),
    }
}

fn map_dns_tester_error(error: CoreError<CydError, Infallible>) -> Error {
    match error {
        CoreError::Display(error) => map_ui_error(error),
        CoreError::Touch(error) => error.into(),
        CoreError::Dns(error) => match error {},
    }
}
