// @generated by cargo xtask generate-board-examples
//! Touch-triggered Wi-Fi/DNS reliability tester.
//!
//! Tap anywhere on the panel to fire one DNS query and update a running tally
//! of hits/misses and the last round-trip latency on a single status line.
//! Meant to run for hours unattended on hardware with no reachable physical
//! reset button, repeatedly exercising the touch driver and the Wi-Fi stack
//! together so long-run failures (socket exhaustion, dropped connections,
//! stuck touch reads) show up on screen instead of silently wedging the
//! board. The status line stays deliberately small: a full-screen frame
//! buffer plus the Wi-Fi stack's own heap overflows plain ESP32's DRAM.
//!
//! Wiring: the classic CYD board's built-in ILI9341 display and XPT2046
//! touch controller, fixed at the factory (see `device_envoy_esp::cyd`
//! module docs for the CYD abstraction):
//!
//! - Display SPI SCK  -> GPIO14
//! - Display SPI MOSI -> GPIO13
//! - Display SPI MISO -> GPIO12
//! - Display CS       -> GPIO15
//! - Display DC       -> GPIO2
//! - Display RST      -> GPIO4
//! - Display backlight -> GPIO21
//! - Touch SPI SCK    -> GPIO25
//! - Touch SPI MOSI   -> GPIO32
//! - Touch SPI MISO   -> GPIO39
//! - Touch CS         -> GPIO33
//! - Touch IRQ        -> GPIO36
//! - Button (Wi-Fi reset while connecting; calibration backup afterward) -> GPIO0
//!   to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;
use embassy_net::dns::DnsQueryType;
use embassy_time::{Duration, Instant, Timer};
use esp_backtrace as _;
use log::{info, warn};

use device_envoy_core::cyd::touch::calibration::CalibrationConfig;
use device_envoy_core::cyd::touch::calibration::{CALIBRATION_MIN_PIXEL_COUNT, ensure_calibration};
use device_envoy_core::cyd::{Cyd as _, CydParts as _, display::Orientation};
use device_envoy_core::dns_lookup::{DnsLookupFn, DnsLookupResult};
use device_envoy_core::flash_block::FlashBlock as _;
use device_envoy_esp::{
    Error, Result,
    button::{Button as _, ButtonEsp, PressedTo},
    cyd::{CydEsp, CydEspUncalibrated, CydStaticEsp, DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT},
    flash_block::FlashBlockEsp,
    init_and_start,
    wifi_auto::{WifiAuto as _, WifiAutoEsp, WifiAutoEvent},
};
use device_envoy_examples_core::dns_tester::{
    Exit as CoreExit, display_orientation_for_calibration, dns_tester, dns_tester_splash,
    render_notice,
};

esp_bootloader_esp_idf::esp_app_desc!();

const DNS_HOSTNAME: &str = "example.com";
const CAPTIVE_PORTAL_SSID: &str = "DeviceEnvoySetup";
/// `ensure_calibration`'s own on-screen text banner needs a buffer at least
/// `CALIBRATION_MIN_PIXEL_COUNT` pixels; its crosshair/dot geometry streams
/// buffer-free. The DNS status line uses the same small-buffer budget.
const STATUS_PIXEL_COUNT: usize = CALIBRATION_MIN_PIXEL_COUNT;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD DNS tester on ESP32 / generic");

    let [
        wifi_auto_flash_block,
        mut calibration_flash_block,
        mut orientation_flash_block,
    ] = FlashBlockEsp::new_array::<3>(p.FLASH)?;
    let orientation = orientation_flash_block
        .load::<Orientation>()?
        .unwrap_or(Orientation::Landscape);
    let calibration_is_available = match calibration_flash_block.load::<CalibrationConfig>() {
        Ok(Some(_)) => true,
        Ok(None) | Err(_) => false,
    };
    let display_orientation =
        display_orientation_for_calibration(orientation, calibration_is_available);
    let mut button = ButtonEsp::new(p.GPIO0, PressedTo::Ground);

    static CYD_STATIC: CydStaticEsp<STATUS_PIXEL_COUNT> = CydEsp::new_static();
    let CydEspUncalibrated { mut display, touch } = CydEspUncalibrated::new(
        &CYD_STATIC,
        p.SPI2,
        p.GPIO14,
        p.GPIO13,
        p.GPIO12,
        p.GPIO15,
        p.GPIO2,
        p.GPIO4,
        p.GPIO21,
        DEFAULT_DISPLAY_SPI_HZ,
        display_orientation,
        embedded_graphics::pixelcolor::Rgb888::new(10, 10, 12), // near-black
        embedded_graphics::pixelcolor::Rgb888::new(230, 230, 230), // near-white
        &DEFAULT_FONT,
        p.SPI3,
        p.GPIO25,
        p.GPIO32,
        p.GPIO39,
        p.GPIO33,
        p.GPIO36,
    )?;
    info!("CYD display and touch initialized");

    let (touch, calibration_outcome) = ensure_calibration(
        &mut display,
        touch,
        &mut calibration_flash_block,
        &mut button,
        Some("recalibrating"),
    )
    .await?;
    if calibration_outcome.was_saved() {
        while button.is_pressed() {
            Timer::after(Duration::from_millis(10)).await;
        }
        info!("Calibration saved, restarting");
        device_envoy_esp::esp_hal::system::software_reset();
    }
    info!("Touch calibrated");

    let mut cyd = CydEsp::from_parts(display, touch);
    dns_tester_splash(cyd.display(), orientation)
        .await
        .map_err(|error| match error {
            device_envoy_examples_core::dns_tester::Error::Text(_) => Error::FormatError,
            device_envoy_examples_core::dns_tester::Error::Display(error) => error.into(),
        })?;

    let wifi_auto = WifiAutoEsp::new(
        p.WIFI,
        wifi_auto_flash_block,
        CAPTIVE_PORTAL_SSID,
        [],
        spawner,
    )?;
    let stack = wifi_auto
        .connect(&mut button, async |wifi_auto_event| -> Result<(), Error> {
            let message = match wifi_auto_event {
                WifiAutoEvent::CaptivePortalReady => {
                    render_notice(
                        cyd.display(),
                        orientation,
                        device_envoy_examples_core::dns_tester::UiNotice::WifiSetup,
                    )
                    .await
                    .map_err(|error| match error {
                        device_envoy_examples_core::dns_tester::Error::Text(_) => {
                            Error::FormatError
                        }
                        device_envoy_examples_core::dns_tester::Error::Display(error) => {
                            error.into()
                        }
                    })?;
                    "WiFi setup: join DeviceEnvoySetup"
                }
                WifiAutoEvent::Connecting { .. } => "Connecting to WiFi...",
                WifiAutoEvent::ConnectionFailed => "WiFi connect failed, retrying",
            };
            info!("Wi-Fi: {message}");
            Ok(())
        })
        .await?;

    while !stack.is_link_up() || stack.config_v4().is_none() {
        Timer::after(Duration::from_millis(200)).await;
    }
    info!("Wi-Fi up with DHCP: {:?}", stack.config_v4());

    let mut dns_lookup = DnsLookupFn(async |hostname: &str| {
        let query_start = Instant::now();
        let dns_result = stack.dns_query(hostname, DnsQueryType::A).await;
        let latency_millis = query_start.elapsed().as_millis();
        let succeeded = match dns_result {
            Ok(addresses) if !addresses.is_empty() => {
                info!("DNS ok in {latency_millis}ms: {:?}", addresses.first());
                true
            }
            Ok(_) => {
                warn!("DNS query returned no addresses");
                false
            }
            Err(_) => {
                warn!("DNS query failed");
                false
            }
        };
        Ok::<DnsLookupResult, Infallible>(DnsLookupResult {
            succeeded,
            latency_millis,
        })
    });
    let exit = dns_tester(&mut cyd, &mut button, DNS_HOSTNAME, &mut dns_lookup)
        .await
        .map_err(|error| match error {
            device_envoy_examples_core::dns_tester::Error::Display(error) => match error {
                device_envoy_examples_core::dns_tester::Error::Text(_) => Error::FormatError,
                device_envoy_examples_core::dns_tester::Error::Display(error) => error.into(),
            },
            device_envoy_examples_core::dns_tester::Error::Touch(error) => error.into(),
            device_envoy_examples_core::dns_tester::Error::Dns(error) => match error {},
        })?;
    match exit {
        CoreExit::CalibrationRequested => {
            calibration_flash_block.clear()?;
        }
        CoreExit::WifiResetRequested => {
            wifi_auto.reset_to_captive_portal()?;
        }
        CoreExit::OrientationChanged(next_orientation) => {
            orientation_flash_block.save(&next_orientation)?;
        }
    }
    device_envoy_esp::esp_hal::system::software_reset();
}
