use std::error::Error;
use std::fs;
use std::path::Path;

const GENERATED_CONTENTS: &str = r#"// @generated by `cargo check-all`. Do not edit by hand.
//! Module containing generated LCD text sample types.
//!
//! Auto-generated.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::i2cs;

#[cfg(all(not(doc), not(feature = "host")))]
i2cs! {
    i2c: I2C0,
    sda_pin: PIN_4,
    scl_pin: PIN_5,
    pub I2csGenerated {
        pub LcdTextGenerated { width: 16, height: 2, address: 0x27 },
        pub LcdTextGenerated20x4 { width: 20, height: 4, address: 0x3F },
    }
}

#[cfg(doc)]
/// Sample struct type generated by the [`i2cs!`](macro@crate::i2cs) macro.
///
/// This page exists to show constructor and methods in one place.
/// For narrative examples, see the [`lcd_text`](mod@crate::lcd_text) module.
///
/// Auto-generated.
pub struct LcdTextGenerated;

#[cfg(doc)]
use crate::Result;

#[cfg(doc)]
/// Sample I2C LCD group type generated by [`i2cs!`](macro@crate::i2cs).
pub struct I2csGenerated;

#[cfg(doc)]
/// Sample LCD text struct type generated by [`i2cs!`](macro@crate::i2cs).
pub struct LcdTextGenerated20x4;

#[cfg(doc)]
impl I2csGenerated {
    /// Construct all generated LCD text devices in this group.
    pub fn new(
        i2c_peripheral: embassy_rp::Peri<'static, embassy_rp::peripherals::I2C0>,
        sda: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_4>,
        scl: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_5>,
        spawner: embassy_executor::Spawner,
    ) -> Result<(&'static LcdTextGenerated, &'static LcdTextGenerated20x4)> {
        static INSTANCE_16X2: LcdTextGenerated = LcdTextGenerated;
        static INSTANCE_20X4: LcdTextGenerated20x4 = LcdTextGenerated20x4;
        let _ = (i2c_peripheral, sda, scl, spawner);
        Ok((&INSTANCE_16X2, &INSTANCE_20X4))
    }
}

#[cfg(doc)]
impl LcdTextGenerated {
    /// Display width in characters.
    pub const WIDTH: usize = 16;
    /// Display height in characters.
    pub const HEIGHT: usize = 2;
    /// LCD I2C address.
    pub const ADDRESS: u8 = 0x27;

    /// Create this generated LCD text instance.
    pub fn new(
        i2c_peripheral: embassy_rp::Peri<'static, embassy_rp::peripherals::I2C0>,
        sda: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_4>,
        scl: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_5>,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: LcdTextGenerated = LcdTextGenerated;
        let _ = (i2c_peripheral, sda, scl, spawner);
        Ok(&INSTANCE)
    }

    /// Write text to the display using clamp-to-frame behavior.
    pub fn write_text(&self, text: impl AsRef<str>) {
        let _ = text;
    }
}

#[cfg(doc)]
impl LcdTextGenerated20x4 {
    /// Display width in characters.
    pub const WIDTH: usize = 20;
    /// Display height in characters.
    pub const HEIGHT: usize = 4;
    /// LCD I2C address.
    pub const ADDRESS: u8 = 0x3F;

    /// Create this generated LCD text instance.
    pub fn new(
        i2c_peripheral: embassy_rp::Peri<'static, embassy_rp::peripherals::I2C0>,
        sda: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_4>,
        scl: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_5>,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: LcdTextGenerated20x4 = LcdTextGenerated20x4;
        let _ = (i2c_peripheral, sda, scl, spawner);
        Ok(&INSTANCE)
    }

    /// Write text to the display using clamp-to-frame behavior.
    pub fn write_text(&self, text: impl AsRef<str>) {
        let _ = text;
    }
}
"#;

pub fn generate_lcd_text_generated(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let output_path = workspace_root.join("src/lcd_text/lcd_text_generated.rs");
    write_if_changed(&output_path, GENERATED_CONTENTS)?;
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == contents => Ok(()),
        _ => {
            fs::write(path, contents)?;
            Ok(())
        }
    }
}
