[env]
DEFMT_LOG = "info"

[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"
xtask-check = "check --manifest-path xtask/Cargo.toml"

check-all = "xtask check-all"
check-quick = "xtask check-quick"
check-examples = "xtask check-examples"
check-demos = "xtask check-demos"
check-compile-only = "xtask check-compile-only"
check-compile-only-tests = "xtask check-compile-only"

test-docs = "test --doc --target thumbv8m.main-none-eabihf --features pico2,wifi,arm --no-default-features"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip=RP2040"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--gc-sections",
]

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip=RP235x"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tcrates/device-envoy-rp/link-rp.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--gc-sections",
]

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=RP235x"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=--gc-sections",
]
