// @generated by cargo xtask generate-board-examples.
#![allow(missing_docs)]
//! ir_example1: not supported on this board profile.
//!
//! Wiring:
//! - this example requires 1 RMT resources, and ESP32-C2 offers 0 RMT resources

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};

use embassy_executor::Spawner;

use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start};

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let _ = spawner;
    info!(
        "ir_example1_esp32c2_devkitm1_v1_0: this example requires 1 RMT resources, and ESP32-C2 offers 0 RMT resources"
    );
    pending().await
}
