//! # LedStripGenerated — Example of a Macro-Generated LED Strip Struct
//!
//! This module demonstrates the exact API shape generated by the [`led_strip!`](crate::led_strip::led_strip) macro.
//! Each time you use the macro, it creates a new struct with the same interface as [`LedStripGenerated`],
//! but with different numbers of LEDs and [PIO](crate#glossary) / [DMA](crate#glossary) resources based on your configuration.
//!
//! **Important:** This is a concrete example struct. Real-world code using `led_strip!` will have custom struct names
//! (e.g., `LedStrip3`, `LedStrip4`) and different LED counts, depending on your macro invocation.
//! See the [`led_strip!`](crate::led_strip::led_strip) macro documentation for how to define your own strips.
//!
//! ## Why Structs Differ
//!
//! Generated structs are specialized for their specific use case:
//! - **Number of LEDs** — Each struct is optimized for exactly one LED count (set via `len` parameter)
//! - **[PIO](crate#glossary) and [DMA](crate#glossary) resources** — Customized to the pins and channels you specify
//!
//! This means mixing different LED counts requires separate type definitions. The compiler prevents mistakes
//! by generating distinct types.
//!
//! ## LedStripGenerated — This Struct
//!
//! `LedStripGenerated` is a 48-LED strip example. It demonstrates:
//! - Associated constants: `LEN`, `MAX_FRAMES`, `MAX_BRIGHTNESS`
//! - Constructor signature: `new(pin, pio, dma, spawner)`
//! - Methods accessed via [`Deref`](core::ops::Deref) to [`LedStrip`](crate::led_strip::LedStrip)
//!
//! ## Associated Constants
//!
//! See the struct documentation for [`LEN`](LedStripGenerated::LEN), [`MAX_FRAMES`](LedStripGenerated::MAX_FRAMES),
//! and [`MAX_BRIGHTNESS`](LedStripGenerated::MAX_BRIGHTNESS).
//!
//! ## Methods (via Deref)
//!
//! All LED control is accessed through [`Deref`](core::ops::Deref) to [`LedStrip`](crate::led_strip::LedStrip):
//!
//! - [`write_frame`](crate::led_strip::LedStrip::write_frame) —
//!   Display a [`Frame`](crate::led_strip::Frame) immediately, replacing any current animation.
//!   Returns `async Result<()>`.
//!
//! - [`animate`](crate::led_strip::LedStrip::animate) —
//!   Loop through a sequence of timed frames until interrupted.
//!   Accepts `impl IntoIterator<Item = (Frame, Duration)>`.
//!   Returns `async Result<()>`.
//!
//! See [`LedStrip`](crate::led_strip::LedStrip) for complete method documentation.
//!
//! ## Example 1: Write a Single Frame
//!
//! Define a 48-LED strip and set every second LED to blue:
//!
//! ```rust,no_run
//! # #![no_std]
//! # #![no_main]
//! # use panic_probe as _;
//! # use core::convert::Infallible;
//! # use core::default::Default;
//! # use core::future;
//! # use core::result::Result::Ok;
//! # use embassy_executor::Spawner;
//! use device_kit::{Result, led_strip::{Frame, colors, led_strip}};
//!
//! led_strip! {
//!     LedStrip3 {
//!         pin: PIN_3,
//!         len: 48,
//!     }
//! }
//!
//! async fn example(spawner: Spawner) -> Result<Infallible> {
//!     let p = embassy_rp::init(Default::default());
//!
//!     let led_strip3 = LedStrip3::new(p.PIN_3, p.PIO0, p.DMA_CH0, spawner)?;
//!
//!     let mut frame = Frame::new();
//!     for pixel_index in (0..frame.len()).step_by(2) {
//!         frame[pixel_index] = colors::BLUE;
//!     }
//!     led_strip3.write_frame(frame).await?;
//!
//!     Ok(future::pending().await) // run forever
//! }
//! ```
//!
//! See the [`led_strip!`](crate::led_strip::led_strip) macro documentation for all configuration options
//! (PIO block selection, DMA channel, current limiting, gamma correction, animation frame count).
//!
//! ## Example 2: Animate a Sequence of Frames
//!
//! Use all optional fields of [`led_strip!`](crate::led_strip::led_strip). Animate a 96-LED strip through red, green, and blue:
//!
//! ```rust,no_run
//! # #![no_std]
//! # #![no_main]
//! # use panic_probe as _;
//! # use core::convert::Infallible;
//! # use core::default::Default;
//! # use core::future;
//! # use core::result::Result::Ok;
//! # use embassy_executor::Spawner;
//! use embassy_time::Duration;
//! use device_kit::{
//!     Result,
//!     led_strip::{Current, Frame, Gamma, colors, led_strip},
//! };
//!
//! led_strip! {
//!     LedStrip4 {
//!         pin: PIN_4,
//!         len: 96,
//!         pio: PIO1,
//!         dma: DMA_CH3,
//!         max_current: Current::Milliamps(1000),
//!         gamma: Gamma::Linear,
//!         max_frames: 3,
//!     }
//! }
//!
//! async fn animate_example(spawner: Spawner) -> Result<Infallible> {
//!     let p = embassy_rp::init(Default::default());
//!     let led_strip4 = LedStrip4::new(p.PIN_4, p.PIO1, p.DMA_CH3, spawner)?;
//!
//!     let frame_duration = Duration::from_millis(300);
//!
//!     led_strip4
//!         .animate([
//!             (Frame::filled(colors::RED), frame_duration),
//!             (Frame::filled(colors::GREEN), frame_duration),
//!             (Frame::filled(colors::BLUE), frame_duration),
//!         ])
//!         .await?;
//!
//!     Ok(future::pending().await) // run forever
//! }
//! ```
//!
//! ## Related
//!
//! - [`led_strip!`](crate::led_strip::led_strip) — Macro documentation explaining all configuration options
//! - [`led_strips!`](crate::led_strip::led_strips) — Create multiple strips sharing one [PIO](crate#glossary) resource
//! - [`LedStrip`](crate::led_strip::LedStrip) — Core LED strip interface with all control methods

use crate::led_strip;

led_strip! {
    LedStripGenerated {
        pin: PIN_3,
        len: 48,
    }
}
