// @generated by cargo xtask generate-board-examples
#![allow(missing_docs)]
//! Talk 1 demo: 8-pixel strip, alternating blink animation.
//!
//! Wiring:
//! - NeoPixel-style (WS2812) strip data input -> GPIO10
//! - Strip power -> 5V (or per strip spec), shared GND with board

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending, panic};

use device_envoy_esp::{
    Result, init_and_start, led_strip,
    led_strip::{Frame1d, LedStrip as _, colors},
};
use embassy_executor::Spawner;
use embassy_time::Duration;
use esp_backtrace as _;

led_strip! {
    LedStripLen8 {
        pin: GPIO10,
        len: 8,
    }
}

esp_bootloader_esp_idf::esp_app_desc!();

// Nice trick: Two "mains" lets us use Results.
#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Blocking);
    let led_strip_len8 = LedStripLen8::new(p.GPIO10, rmt80.channel0, spawner)?;

    // Create two frames
    let palette = [colors::BLUE, colors::LIGHT_GRAY];
    let mut frame0 = Frame1d::new();
    let mut frame1 = frame0.clone();
    for pixel_index in 0..frame0.len() {
        frame0[pixel_index] = palette[pixel_index % 2];
        frame1[pixel_index] = palette[(pixel_index + 1) % 2];
    }

    // Animate between the two frames forever until replaced
    const FRAME_DURATION: Duration = Duration::from_millis(150);
    led_strip_len8.animate([(frame0, FRAME_DURATION), (frame1, FRAME_DURATION)]);

    // Could do more things here. The animation runs in the background.

    pending().await // run forever
}
