// @generated by cargo xtask generate-board-examples
//! Calibrates the touch panel once (persisting the result to flash) and then
//! paints a small filled circle at every touch point — a minimal interactive
//! demo of `device_envoy_esp::cyd`'s calibration flow and calibrated touch
//! event stream.
//!
//! Wiring: the classic CYD board's built-in ILI9341 display and XPT2046
//! touch controller, fixed at the factory (see `device_envoy_esp::cyd`
//! module docs for the CYD abstraction):
//!
//! - Display SPI SCK  -> GPIO14
//! - Display SPI MOSI -> GPIO13
//! - Display SPI MISO -> GPIO12
//! - Display CS       -> GPIO15
//! - Display DC       -> GPIO2
//! - Display RST      -> GPIO4
//! - Display backlight -> GPIO21
//! - Touch SPI SCK    -> GPIO25
//! - Touch SPI MOSI   -> GPIO32
//! - Touch SPI MISO   -> GPIO39
//! - Touch CS         -> GPIO33
//! - Touch IRQ        -> GPIO36
//! - Recalibration button -> GPIO0 to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use embedded_graphics::{
    Drawable,
    pixelcolor::{Rgb565, Rgb888},
    prelude::Point,
    primitives::{Circle, Primitive, PrimitiveStyle},
};
use esp_backtrace as _;
use log::info;

use device_envoy_core::cyd::touch::calibration::ensure_calibration;
use device_envoy_esp::{
    Result,
    button::{ButtonEsp, PressedTo},
    cyd::{
        CydDisplay as _, CydEsp, CydEspUncalibrated, CydStaticEsp, CydTouch as _,
        DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT, Orientation,
    },
    flash_block::FlashBlockEsp,
    init_and_start,
};

esp_bootloader_esp_idf::esp_app_desc!();

const TOUCH_DOT_RADIUS: u32 = 5;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(_spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD touch-paint demo");

    let [mut calibration_flash_block] = FlashBlockEsp::new_array::<1>(p.FLASH)?;
    let mut recalibration_button = ButtonEsp::new(p.GPIO0, PressedTo::Ground);

    static CYD_STATIC: CydStaticEsp<{ CydEsp::SCREEN_PIXELS }> = CydEsp::new_static();
    let CydEspUncalibrated { mut display, touch } = CydEspUncalibrated::new(
        &CYD_STATIC,
        p.SPI2,
        p.GPIO14,
        p.GPIO13,
        p.GPIO12,
        p.GPIO15,
        p.GPIO2,
        p.GPIO4,
        p.GPIO21,
        DEFAULT_DISPLAY_SPI_HZ,
        Orientation::Landscape,
        Rgb888::new(10, 10, 12),
        Rgb888::new(230, 230, 230),
        &DEFAULT_FONT,
        p.SPI3,
        p.GPIO25,
        p.GPIO32,
        p.GPIO39,
        p.GPIO33,
        p.GPIO36,
    )?;
    info!("CYD display and touch initialized");

    let (mut touch, calibration_outcome) = ensure_calibration(
        &mut display,
        touch,
        &mut calibration_flash_block,
        &mut recalibration_button,
        Some("recalibrating"),
    )
    .await?;
    if calibration_outcome.was_saved() {
        info!("Calibration saved, restarting");
        device_envoy_esp::esp_hal::system::software_reset();
    }
    info!("Touch calibrated; tap the panel to paint");

    let mut frame = display.full_frame_mut();
    frame.flush()?;

    loop {
        if let Some(touch_event) = touch.read()? {
            let point = match touch_event {
                device_envoy_esp::cyd::touch::TouchEvent::Down { point }
                | device_envoy_esp::cyd::touch::TouchEvent::Move { point } => Some(point),
                device_envoy_esp::cyd::touch::TouchEvent::Up => None,
            };
            if let Some(point) = point {
                Circle::with_center(Point::new(point.x, point.y), TOUCH_DOT_RADIUS * 2)
                    .into_styled(PrimitiveStyle::with_fill(Rgb565::new(28, 50, 12)))
                    .draw(&mut frame)
                    .expect("drawing onto an Infallible CYD frame cannot fail");
                frame.flush()?;
            }
        }
        Timer::after(Duration::from_millis(16)).await;
    }
}
