// @generated by cargo xtask generate-board-examples
//!
//! Wiring:
//! - Follow the board-specific pin mapping shown in this file.
#![allow(missing_docs)]
#![no_std]
#![no_main]

use core::convert::Infallible;

use esp_backtrace as _;

use device_envoy_esp::{
    Result, init_and_start, ir,
    ir::{Ir, IrEvent},
};

esp_bootloader_esp_idf::esp_app_desc!();

ir! {
    IrBoard {
        pin: GPIO4
    }
}

async fn handle_ir_presses(ir: &impl Ir) -> ! {
    loop {
        let ir_event = ir.wait_for_press().await;
        match ir_event {
            IrEvent::Press { addr, cmd } => {
                // Handle decoded NEC press event.
                let _ = (addr, cmd);
            }
        }
    }
}

#[esp_rtos::main]
async fn main(spawner: embassy_executor::Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: embassy_executor::Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Async);

    let channel_creator = rmt80.channel2;
    let ir_board = IrBoard::new(p.GPIO4, channel_creator, spawner)?;

    handle_ir_presses(ir_board).await
}
