// @generated - manually created as documentation example. Do not auto-generate.
//! Module containing [`ButtonWatchGenerated`], the sample struct type generated by the
//! [`button_watch!`](crate::button_watch!) macro.
//!
//! This file shows what the macro expansion looks like for documentation purposes.

#[cfg(all(not(doc), not(feature = "host"), target_os = "none"))]
use crate::button_watch;

#[cfg(all(not(doc), not(feature = "host"), target_os = "none"))]
button_watch! {
    pub ButtonWatchGenerated {
        pin: GPIO13,
    }
}

#[cfg(doc)]
/// Sample struct type generated by the [`button_watch!`](crate::button_watch!) macro, showing all methods.
///
/// This page serves as the definitive reference for what a generated button watch type
/// provides. For first-time readers, start with the examples in the [`button_watch!`](crate::button_watch!)
/// macro documentation, then return here for a complete list of available methods.
pub struct ButtonWatchGenerated {
    button_watch: super::ButtonWatchEsp<'static>,
}

#[cfg(doc)]
impl ButtonWatchGenerated {
    /// Creates a new button monitor and spawns its background task.
    ///
    /// # Parameters
    ///
    /// - `button_pin`: GPIO pin for the button
    /// - `pressed_to`: How the button is wired ([`PressedTo::Ground`](crate::button::PressedTo::Ground) or [`PressedTo::Voltage`](crate::button::PressedTo::Voltage))
    /// - `spawner`: Task spawner for background operations
    ///
    /// # Errors
    ///
    /// Returns an error if the background task cannot be spawned.
    ///
    /// # Example
    ///
    /// See the [`button_watch!`](crate::button_watch!) macro for usage.
    pub fn new(
        button_pin: crate::esp_hal::peripherals::GPIO13<'static>,
        pressed_to: crate::button::PressedTo,
        spawner: embassy_executor::Spawner,
    ) -> crate::Result<&'static mut Self> {
        static INSTANCE: static_cell::StaticCell<ButtonWatchGenerated> = static_cell::StaticCell::new();
        let instance = INSTANCE.init(ButtonWatchGenerated {
            button_watch: super::ButtonWatchEsp {
                signal: &embassy_sync::signal::Signal::new(),
                state_signal: &embassy_sync::signal::Signal::new(),
                is_pressed: &core::sync::atomic::AtomicBool::new(false),
            },
        });
        let _ = (button_pin, pressed_to, spawner);
        Ok(instance)
    }

    /// Creates a monitor from an existing button.
    ///
    /// # Parameters
    ///
    /// - `button`: Existing button instance
    /// - `spawner`: Task spawner for background operations
    ///
    /// # Errors
    ///
    /// Returns an error if the background task cannot be spawned.
    pub fn from_button(
        button: crate::button::ButtonEsp<'static>,
        spawner: embassy_executor::Spawner,
    ) -> crate::Result<&'static mut Self> {
        static INSTANCE: static_cell::StaticCell<ButtonWatchGenerated> = static_cell::StaticCell::new();
        let instance = INSTANCE.init(ButtonWatchGenerated {
            button_watch: super::ButtonWatchEsp {
                signal: &embassy_sync::signal::Signal::new(),
                state_signal: &embassy_sync::signal::Signal::new(),
                is_pressed: &core::sync::atomic::AtomicBool::new(false),
            },
        });
        let _ = (button, spawner);
        Ok(instance)
    }
}

#[cfg(doc)]
impl core::ops::Deref for ButtonWatchGenerated {
    type Target = super::ButtonWatchEsp<'static>;

    fn deref(&self) -> &Self::Target {
        &self.button_watch
    }
}

#[cfg(doc)]
impl crate::button::Button for ButtonWatchGenerated {
    fn is_pressed(&self) -> bool {
        <super::ButtonWatchEsp<'static> as crate::button::Button>::is_pressed(&self.button_watch)
    }

    async fn wait_for_press_duration(&mut self) -> crate::button::PressDuration {
        <super::ButtonWatchEsp<'static> as crate::button::Button>::wait_for_press_duration(
            &mut self.button_watch,
        )
        .await
    }

    async fn wait_until_pressed_state(&mut self, pressed: bool) {
        <super::ButtonWatchEsp<'static> as crate::button::Button>::wait_until_pressed_state(
            &mut self.button_watch,
            pressed,
        )
        .await
    }
}
