[alias]
check-all = "run --manifest-path xtask/Cargo.toml -- check-all"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]
