// @generated by xtask check-readme-example. Do not edit.
#![allow(dead_code, missing_docs)]

#![no_std]
#![no_main]
use esp_backtrace as _;
use core::convert::Infallible;
use device_envoy_esp::{Result, init_and_start, led_strip, led_strip::{LedStrip as _, Frame1d, colors}};
#[cfg(not(esp_has_rmt))]
#[allow(unused_imports)]
use device_envoy_esp::led_strip::Engine;
use embassy_time::Duration;

#[cfg(esp_has_rmt)]
led_strip! {
    LedStripAnimated {
        pin: GPIO0,
        len: 96,
    }
}

#[cfg(not(esp_has_rmt))]
led_strip! {
    LedStripAnimated {
        pin: GPIO0,
        len: 96,
        engine: Engine::Spi,
    }
}

async fn example(spawner: embassy_executor::Spawner) -> Result<Infallible> {
    #[cfg(esp_has_rmt)]
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Blocking);
    #[cfg(not(esp_has_rmt))]
    init_and_start!(p);

    #[cfg(esp_has_rmt)]
    let led_strip_animated = LedStripAnimated::new(p.GPIO0, rmt80.channel0, spawner)?;
    #[cfg(not(esp_has_rmt))]
    let led_strip_animated = LedStripAnimated::new(p.GPIO0, p.SPI2, spawner)?;

    // Create a sequence of frames and durations and then animate them (looping, until replaced).
    let frame_duration = Duration::from_millis(300);
    led_strip_animated.animate([
        (Frame1d::filled(colors::RED), frame_duration),
        (Frame1d::filled(colors::GREEN), frame_duration),
        (Frame1d::filled(colors::BLUE), frame_duration),
    ]);

    core::future::pending().await // run forever
}