// @generated by cargo xtask generate-board-examples.
#![allow(missing_docs)]
//! clock_sync_example1_trait: not supported on this board profile.
//!
//! Wiring:
//! - this example requires Wi-Fi, and ESP32-H2 does not offer that resource

#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;

use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start};

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let _ = spawner;
    info!(
        "clock_sync_example1_trait_esp32h2_generic: this example requires Wi-Fi, and ESP32-H2 does not offer that resource"
    );
    core::future::pending().await
}
