// @generated by cargo xtask generate-board-examples.
//! audio_example3: not supported on this board profile.
//!
//! Wiring:
//! - this example requires I2S resources, and ESP32-C61 does not offer that resource

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};

use embassy_executor::Spawner;

use esp_backtrace as _;
use log::info;

use device_envoy_esp::{init_and_start, Result};

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let _ = spawner;
    info!(
        "audio_example3_esp32c61_generic: this example requires I2S resources, and ESP32-C61 does not offer that resource"
    );
    pending().await
}
