
// @generated by cargo xtask generate-board-examples
//! SunFounder Kepler IR remote demo with two receivers.
//!
//! Wiring:
//! - IR receiver #0 data output -> GPIO7
//! - IR receiver #1 data output -> GPIO4
//! - Both receiver VCC pins -> 3.3V
//! - Both receiver GND pins -> GND

#![no_std]
#![no_main]

use core::convert::Infallible;
use embassy_executor::Spawner;
use embassy_futures::select::{select, Either};
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{init_and_start, ir::IrKepler as _, ir_keplers, Result};

esp_bootloader_esp_idf::esp_app_desc!();

ir_keplers! {
    IrKeplersBoard {
        IrKeplerReceiver0: { pin: GPIO7 },
        IrKeplerReceiver1: { pin: GPIO4 }
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Async);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let channel_creator0 = rmt80.channel2;
    let channel_creator1 = rmt80.channel3;

    let (ir_kepler_receiver0, ir_kepler_receiver1) = IrKeplersBoard::new(
        p.GPIO7,
        channel_creator0,
        p.GPIO4,
        channel_creator1,
        spawner,
    )?;

    info!("Kepler remotes initialized");

    loop {
        match select(
            ir_kepler_receiver0.wait_for_press(),
            ir_kepler_receiver1.wait_for_press(),
        )
        .await
        {
            Either::First(button0) => info!("Kepler receiver 0 button: {:?}", button0),
            Either::Second(button1) => info!("Kepler receiver 1 button: {:?}", button1),
        }
    }
}