use std::error::Error;
use std::fs;
use std::path::Path;

const GENERATED_CONTENTS: &str = r#"// @generated by `cargo check-all`. Do not edit by hand.
//! Module containing [`AdpcmPlayerGenerated`], the sample struct type generated
//! by the [`adpcm_player!`](macro@crate::adpcm_player::adpcm_player) macro.
//!
//! Auto-generated.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::adpcm_player;

#[cfg(all(not(doc), not(feature = "host")))]
adpcm_player! {
    pub AdpcmPlayerGenerated {
        data_pin: PIN_8,
        bit_clock_pin: PIN_9,
        word_select_pin: PIN_10,
        sample_rate_hz: crate::audio_player::VOICE_22050_HZ,
    }
}

#[cfg(doc)]
/// Sample struct type generated by the [`adpcm_player!`](macro@crate::adpcm_player::adpcm_player)
/// macro, showing methods and associated constants.
///
/// Auto-generated.
pub struct AdpcmPlayerGenerated;

#[cfg(doc)]
/// Unsized ADPCM clip type at [`AdpcmPlayerGenerated::SAMPLE_RATE_HZ`].
pub type AdpcmPlayerGeneratedAdpcmClip = crate::adpcm_player::AdpcmClip<22_050>;

#[cfg(doc)]
use crate::Result;
#[cfg(doc)]
use crate::adpcm_player::{AtEnd, AdpcmClip, Volume};

#[cfg(doc)]
impl AdpcmPlayerGenerated {
    /// Sample rate used for ADPCM playback by this generated player type.
    pub const SAMPLE_RATE_HZ: u32 = 22_050;
    /// Initial runtime volume relative to [`Self::MAX_VOLUME`].
    pub const INITIAL_VOLUME: Volume = Volume::MAX;
    /// Runtime volume ceiling for this generated player type.
    pub const MAX_VOLUME: Volume = Volume::MAX;

    /// Creates and spawns the generated ADPCM player instance.
    pub fn new(
        data_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_8>,
        bit_clock_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_9>,
        word_select_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_10>,
        pio: embassy_rp::Peri<'static, embassy_rp::peripherals::PIO1>,
        dma: embassy_rp::Peri<'static, embassy_rp::peripherals::DMA_CH0>,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: AdpcmPlayerGenerated = AdpcmPlayerGenerated;
        let _ = (data_pin, bit_clock_pin, word_select_pin, pio, dma, spawner);
        Ok(&INSTANCE)
    }

    /// Starts playback of one or more static ADPCM clips.
    pub fn play<const CLIP_COUNT: usize>(
        &self,
        adpcm_clips: [&'static AdpcmClip<{ Self::SAMPLE_RATE_HZ }>; CLIP_COUNT],
        at_end: AtEnd,
    ) {
        let _ = (adpcm_clips, at_end);
    }

    /// Stops current playback as soon as possible.
    pub fn stop(&self) {}

    /// Sets runtime playback volume.
    pub fn set_volume(&self, volume: Volume) {
        let _ = volume;
    }

    /// Returns the current runtime playback volume.
    #[must_use]
    pub fn volume(&self) -> Volume {
        Volume::MAX
    }
}
"#;

pub fn generate_adpcm_player_generated(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let output_path = workspace_root.join("src/adpcm_player/adpcm_player_generated.rs");
    write_if_changed(&output_path, GENERATED_CONTENTS)?;
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == contents {
            return Ok(());
        }
    }
    fs::write(path, contents)?;
    Ok(())
}
