use std::error::Error;
use std::fs;
use std::path::Path;

const GENERATED_CONTENTS: &str = r#"// @generated by `cargo check-all`. Do not edit by hand.
//! Module containing [`AudioClipGenerated`], the sample module generated by
//! the [`audio_clip!`](macro@crate::audio_player::audio_clip) macro.
//!
//! Auto-generated.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::audio_player::audio_clip;

#[cfg(all(not(doc), not(feature = "host")))]
audio_clip! {
    pub AudioClipGenerated {
        sample_rate_hz: crate::audio_player::VOICE_22050_HZ,
        file: "../../examples/data/audio/nasa_22k.s16",
        format: crate::audio_player::AudioFormat::S16le,
    }
}

#[cfg(doc)]
#[allow(non_snake_case)]
/// Sample module generated by the [`audio_clip!`](macro@crate::audio_player::audio_clip)
/// macro, showing the generated items.
///
/// This page serves as the reference for what a generated audio clip namespace
/// provides. For first-time readers, start with the
/// [`audio_player`](mod@crate::audio_player) module documentation, then return
/// here for the generated `AudioClip` and `audio_clip()` items.
///
/// The generated items are in a module (not a struct type) because stable Rust
/// does not support inherent associated types on structs.
///
/// Auto-generated.
pub mod AudioClipGenerated {
    use crate::audio_player::{AudioClipBuf, VOICE_22050_HZ};

    /// Concrete return type of `audio_clip()`.
    pub type AudioClip = AudioClipBuf<VOICE_22050_HZ, 92_160>;

    /// `const` function that returns the generated audio clip.
    #[must_use]
    pub const fn audio_clip() -> AudioClip {
        AudioClip::silence()
    }
}
"#;

pub fn generate_audio_clip_generated(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let output_path = workspace_root.join("src/audio_player/audio_clip_generated.rs");
    write_if_changed(&output_path, GENERATED_CONTENTS)?;
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == contents => Ok(()),
        _ => {
            fs::write(path, contents)?;
            Ok(())
        }
    }
}
