use std::error::Error;
use std::fs;
use std::path::Path;

const GENERATED_CONTENTS: &str = r#"// @generated by `cargo check-all`. Do not edit by hand.
//! Module containing [`AudioPlayerGenerated`], the sample struct type generated
//! by the [`audio_player!`](macro@crate::audio_player) macro.
//!
//! Auto-generated.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::audio_player;

#[cfg(all(not(doc), not(feature = "host")))]
audio_player! {
    pub AudioPlayerGenerated {
        data_pin: PIN_8,
        bit_clock_pin: PIN_9,
        word_select_pin: PIN_10,
        sample_rate_hz: crate::audio_player::VOICE_22050_HZ,
    }
}

#[cfg(doc)]
/// Sample struct type generated by the [`audio_player!`](macro@crate::audio_player)
/// macro, showing methods and associated constants.
///
/// This page serves as the reference for what a generated audio player type
/// provides. For first-time readers, start with the
/// [`audio_player`](mod@crate::audio_player) module documentation, then return
/// here for a complete list of available methods, associated constants, and
/// generated type aliases.
///
/// The macro also generates [`AudioPlayerGeneratedAudioClip`], a type alias for
/// [`AudioClip`] at
/// [`AudioPlayerGenerated::SAMPLE_RATE_HZ`].
///
/// Auto-generated.
pub struct AudioPlayerGenerated;

#[cfg(doc)]
/// Unsized clip type at [`AudioPlayerGenerated::SAMPLE_RATE_HZ`].
///
/// See the [audio_player module documentation](mod@crate::audio_player) for
/// usage examples.
pub type AudioPlayerGeneratedAudioClip = AudioClip<VOICE_22050_HZ>;

#[cfg(doc)]
use crate::Result;
#[cfg(doc)]
use crate::audio_player::{AtEnd, AudioClip, AudioClipBuf, Volume, VOICE_22050_HZ};

#[cfg(doc)]
impl AudioPlayerGenerated {
    /// Sample rate used for PCM playback by this generated player type.
    pub const SAMPLE_RATE_HZ: u32 = VOICE_22050_HZ;
    /// Initial runtime volume relative to [`Self::MAX_VOLUME`].
    pub const INITIAL_VOLUME: Volume = Volume::MAX;
    /// Runtime volume ceiling for this generated player type.
    pub const MAX_VOLUME: Volume = Volume::MAX;

    /// Returns how many samples are needed for a duration in milliseconds
    /// at this player's sample rate.
    #[must_use]
    pub const fn samples_ms(duration_ms: u32) -> usize {
        crate::audio_player::samples_for_duration_ms(duration_ms, Self::SAMPLE_RATE_HZ)
    }

    /// Creates a silent clip at this player's sample rate.
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    #[must_use]
    pub const fn silence<const SAMPLE_COUNT: usize>(
    ) -> AudioClipBuf<{ Self::SAMPLE_RATE_HZ }, SAMPLE_COUNT> {
        AudioClipBuf::silence()
    }

    /// Creates a sine-wave clip at this player's sample rate.
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    #[must_use]
    pub const fn tone<const SAMPLE_COUNT: usize>(
        frequency_hz: u32,
    ) -> AudioClipBuf<{ Self::SAMPLE_RATE_HZ }, SAMPLE_COUNT> {
        AudioClipBuf::tone(frequency_hz)
    }

    /// Creates and spawns the generated audio player instance.
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    pub fn new(
        data_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_8>,
        bit_clock_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_9>,
        word_select_pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_10>,
        pio: embassy_rp::Peri<'static, embassy_rp::peripherals::PIO1>,
        dma: embassy_rp::Peri<'static, embassy_rp::peripherals::DMA_CH0>,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: AudioPlayerGenerated = AudioPlayerGenerated;
        let _ = (data_pin, bit_clock_pin, word_select_pin, pio, dma, spawner);
        Ok(&INSTANCE)
    }

    /// Starts playback of one or more static audio clips.
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    pub fn play<const CLIP_COUNT: usize>(
        &self,
        audio_clips: [&'static AudioClip<{ Self::SAMPLE_RATE_HZ }>; CLIP_COUNT],
        at_end: AtEnd,
    ) {
        let _ = (audio_clips, at_end);
    }

    /// Stops current playback as soon as possible.
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    pub fn stop(&self) {}

    /// Sets runtime playback volume relative to [`Self::MAX_VOLUME`].
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    pub fn set_volume(&self, volume: Volume) {
        let _ = volume;
    }

    /// Returns the current runtime playback volume relative to [`Self::MAX_VOLUME`].
    ///
    /// See the [`audio_player`](mod@crate::audio_player) module docs for usage.
    #[must_use]
    pub fn volume(&self) -> Volume {
        Volume::MAX
    }

}
"#;

pub fn generate_audio_player_generated(workspace_root: &Path) -> Result<(), Box<dyn Error>> {
    let output_path = workspace_root.join("src/audio_player/audio_player_generated.rs");
    write_if_changed(&output_path, GENERATED_CONTENTS)?;
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == contents {
            return Ok(());
        }
    }
    fs::write(path, contents)?;
    Ok(())
}
