// @generated by cargo xtask generate-board-examples.
//! cyd_tiles: not supported on this board profile.
//!
//! Wiring:
//! - this example requires 2 SPI resources, and ESP32-C2 offers 1 SPI resource

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};

use embassy_executor::Spawner;

use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start};

esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    let _ = spawner;
    info!(
        "cyd_tiles_esp32c2_generic: this example requires 2 SPI resources, and ESP32-C2 offers 1 SPI resource"
    );
    pending().await
}
