[alias]
xtask = "run --manifest-path xtask/Cargo.toml --target x86_64-unknown-linux-gnu --"
check-all = "xtask check-all"
check-pre-push = "xtask check-pre-push"
check-demos = "xtask check-demos"
check-examples-all-processors = "xtask check-examples-all-processors"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
