[alias]
xtask        = "run --manifest-path xtask/Cargo.toml --target x86_64-unknown-linux-gnu --"
check-all    = "xtask check-all"
blinky           = "run   --example blinky      --target riscv32imac-unknown-none-elf --release --no-default-features"
blinky-check     = "check --example blinky      --target riscv32imac-unknown-none-elf --no-default-features"
led-strip8       = "run   --example led_strip8  --target riscv32imac-unknown-none-elf --release --no-default-features"
led-strip8-check = "check --example led_strip8  --target riscv32imac-unknown-none-elf --no-default-features"
led-strip8-spi       = "run   --example led_strip8_spi  --target riscv32imac-unknown-none-elf --release --no-default-features"
led-strip8-spi-check = "check --example led_strip8_spi  --target riscv32imac-unknown-none-elf --no-default-features"
led-strip-example1-trait = "run   --example led_strip_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
led-strip-example1-trait-check = "check --example led_strip_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
led-strip-example2-trait = "run   --example led_strip_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
led-strip-example2-trait-check = "check --example led_strip_example2_trait --target riscv32imac-unknown-none-elf --no-default-features"
led2d            = "run   --example led2d       --target riscv32imac-unknown-none-elf --release --no-default-features"
led2d-check      = "check --example led2d       --target riscv32imac-unknown-none-elf --no-default-features"
led2d-example1-trait = "run   --example led2d_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
led2d-example1-trait-check = "check --example led2d_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
led2d-example2-trait = "run   --example led2d_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
led2d-example2-trait-check = "check --example led2d_example2_trait --target riscv32imac-unknown-none-elf --no-default-features"
button-read      = "run   --example button_read --target riscv32imac-unknown-none-elf --release --no-default-features"
button-read-check = "check --example button_read --target riscv32imac-unknown-none-elf --no-default-features"
button-example1-trait = "run   --example button_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
button-example1-trait-check = "check --example button_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
char-lcd-simple = "run   --example char_lcd_simple --target riscv32imac-unknown-none-elf --release --no-default-features"
char-lcd-simple-check = "check --example char_lcd_simple --target riscv32imac-unknown-none-elf --no-default-features"
wifi-auto-force-button = "run   --example wifi_auto_force_button --target riscv32imac-unknown-none-elf --release --no-default-features"
wifi-auto-force-button-check = "check --example wifi_auto_force_button --target riscv32imac-unknown-none-elf --no-default-features"
wifi-auto-example1-trait = "run   --example wifi_auto_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
wifi-auto-example1-trait-check = "check --example wifi_auto_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
wifi-scan = "run   --example wifi_scan --target riscv32imac-unknown-none-elf --release --no-default-features"
wifi-scan-check = "check --example wifi_scan --target riscv32imac-unknown-none-elf --no-default-features"
wifi-dns-hex = "run   --example wifi_dns_hex --target riscv32imac-unknown-none-elf --release --no-default-features"
wifi-dns-hex-check = "check --example wifi_dns_hex --target riscv32imac-unknown-none-elf --no-default-features"
clock-led8x12 = "run   --example clock_led8x12 --target riscv32imac-unknown-none-elf --release --no-default-features"
clock-led8x12-check = "check --example clock_led8x12 --target riscv32imac-unknown-none-elf --no-default-features"
clock-led4 = "run   --example clock_led4 --target riscv32imac-unknown-none-elf --release --no-default-features"
clock-led4-check = "check --example clock_led4 --target riscv32imac-unknown-none-elf --no-default-features"
clock-servos = "run   --example clock_servos --target riscv32imac-unknown-none-elf --release --no-default-features"
clock-servos-check = "check --example clock_servos --target riscv32imac-unknown-none-elf --no-default-features"
clock-lcd = "run   --example clock_lcd --target riscv32imac-unknown-none-elf --release --no-default-features"
clock-lcd-check = "check --example clock_lcd --target riscv32imac-unknown-none-elf --no-default-features"
servo-basic = "run   --example servo_basic --target riscv32imac-unknown-none-elf --release --no-default-features"
servo-basic-check = "check --example servo_basic --target riscv32imac-unknown-none-elf --no-default-features"
servo-example1-trait = "run   --example servo_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
servo-example1-trait-check = "check --example servo_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
servo-example1-trait-s3 = "run   --example servo_example1_trait --target xtensa-esp32s3-none-elf --release --no-default-features"
servo-example1-trait-check-s3 = "check --example servo_example1_trait --target xtensa-esp32s3-none-elf --no-default-features"
servo-player-example1-trait = "run   --example servo_player_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
servo-player-example1-trait-check = "check --example servo_player_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
servo-player-example2-trait = "run   --example servo_player_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
servo-player-example2-trait-check = "check --example servo_player_example2_trait --target riscv32imac-unknown-none-elf --no-default-features"
servos = "run   --example servos --target riscv32imac-unknown-none-elf --release --no-default-features"
servos-check = "check --example servos --target riscv32imac-unknown-none-elf --no-default-features"
ir = "run   --example ir --target riscv32imac-unknown-none-elf --release --no-default-features"
ir-check = "check --example ir --target riscv32imac-unknown-none-elf --no-default-features"
ir-example1-trait = "run   --example ir_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
ir-example1-trait-check = "check --example ir_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
ir-mapping-example1-trait = "run   --example ir_mapping_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
ir-mapping-example1-trait-check = "check --example ir_mapping_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
ir-kepler-example1-trait = "run   --example ir_kepler_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
ir-kepler-example1-trait-check = "check --example ir_kepler_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
ir-kepler = "run   --example ir_kepler --target riscv32imac-unknown-none-elf --release --no-default-features"
ir-kepler-check = "check --example ir_kepler --target riscv32imac-unknown-none-elf --no-default-features"
conway = "run   --example conway --target riscv32imac-unknown-none-elf --release --no-default-features"
conway-check = "check --example conway --target riscv32imac-unknown-none-elf --no-default-features"
led16x16test = "run   --example led16x16test --target riscv32imac-unknown-none-elf --release --no-default-features"
led16x16test-check = "check --example led16x16test --target riscv32imac-unknown-none-elf --no-default-features"
led16x16test-async = "run   --example led16x16test_async --target riscv32imac-unknown-none-elf --release --no-default-features"
led16x16test-async-check = "check --example led16x16test_async --target riscv32imac-unknown-none-elf --no-default-features"
led16x16-and-builtin = "run   --example led16x16_and_builtin --target riscv32imac-unknown-none-elf --release --no-default-features"
led16x16-and-builtin-check = "check --example led16x16_and_builtin --target riscv32imac-unknown-none-elf --no-default-features"
led16x16-and-builtin-spi = "run   --example led16x16_and_builtin_spi --target riscv32imac-unknown-none-elf --release --no-default-features"
led16x16-and-builtin-spi-check = "check --example led16x16_and_builtin_spi --target riscv32imac-unknown-none-elf --no-default-features"
audio-example1 = "run   --example audio_example1 --target riscv32imac-unknown-none-elf --release --no-default-features"
audio-example1-check = "check --example audio_example1 --target riscv32imac-unknown-none-elf --no-default-features"
audio-example1-trait = "run   --example audio_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
audio-example1-trait-check = "check --example audio_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
audio-example2-trait = "run   --example audio_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
audio-example2-trait-check = "check --example audio_example2_trait --target riscv32imac-unknown-none-elf --no-default-features"
audio-example3-trait = "run   --example audio_example3_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
audio-example3-trait-check = "check --example audio_example3_trait --target riscv32imac-unknown-none-elf --no-default-features"
flash-block-example1-trait = "run   --example flash_block_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features"
flash-block-example1-trait-check = "check --example flash_block_example1_trait --target riscv32imac-unknown-none-elf --no-default-features"
audio = "run   --example audio --target riscv32imac-unknown-none-elf --release --no-default-features"
audio-check = "check --example audio --target riscv32imac-unknown-none-elf --no-default-features"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
