[alias]
xtask        = "run --manifest-path xtask/Cargo.toml --target x86_64-unknown-linux-gnu --"
check-all    = "xtask check-all"
check-pre-push = "xtask check-pre-push"
check-demos  = "xtask check-demos"
check-examples-all-processors = "xtask check-examples-all-processors"
demo-a1 = "run --package device-envoy-esp-demos --bin demo_a1_strip_8_blue_gray --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-a1-check = "check --package device-envoy-esp-demos --bin demo_a1_strip_8_blue_gray --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-a1-s3 = "+esp run --package device-envoy-esp-demos --bin demo_a1_strip_8_blue_gray --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-a1-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_a1_strip_8_blue_gray --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-a3 = "run --package device-envoy-esp-demos --bin demo_a3_strip_8_blue_white_blink_animate --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-a3-check = "check --package device-envoy-esp-demos --bin demo_a3_strip_8_blue_white_blink_animate --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-a3-s3 = "+esp run --package device-envoy-esp-demos --bin demo_a3_strip_8_blue_white_blink_animate --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-a3-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_a3_strip_8_blue_white_blink_animate --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-a4 = "run --package device-envoy-esp-demos --bin demo_a4_strip_96_blue_white_dot --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-a4-check = "check --package device-envoy-esp-demos --bin demo_a4_strip_96_blue_white_dot --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-a4-s3 = "+esp run --package device-envoy-esp-demos --bin demo_a4_strip_96_blue_white_dot --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-a4-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_a4_strip_96_blue_white_dot --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-b1 = "run --package device-envoy-esp-demos --bin demo_b1_panel_12x8_rust_cursor --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-b1-check = "check --package device-envoy-esp-demos --bin demo_b1_panel_12x8_rust_cursor --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-b1-s3 = "+esp run --package device-envoy-esp-demos --bin demo_b1_panel_12x8_rust_cursor --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-b1-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_b1_panel_12x8_rust_cursor --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-b2 = "run --package device-envoy-esp-demos --bin demo_b2_panel_12x8_text_graphics --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-b2-check = "check --package device-envoy-esp-demos --bin demo_b2_panel_12x8_text_graphics --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-b2-s3 = "+esp run --package device-envoy-esp-demos --bin demo_b2_panel_12x8_text_graphics --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-b2-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_b2_panel_12x8_text_graphics --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-f1 = "run --package device-envoy-esp-demos --bin demo_f1_dns --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
demo-f1-check = "check --package device-envoy-esp-demos --bin demo_f1_dns --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
demo-f1-s3 = "+esp run --package device-envoy-esp-demos --bin demo_f1_dns --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
demo-f1-check-s3 = "+esp check --package device-envoy-esp-demos --bin demo_f1_dns --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3 -Zbuild-std=core,alloc"
blinky           = "run   --example blinky      --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
blinky-check     = "check --example blinky      --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-strip8       = "run   --example led_strip8  --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led-strip8-check = "check --example led_strip8  --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-strip8-spi       = "run   --example led_strip8_spi  --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led-strip8-spi-check = "check --example led_strip8_spi  --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-strip-example1-trait = "run   --example led_strip_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led-strip-example1-trait-check = "check --example led_strip_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-strip-example2-trait = "run   --example led_strip_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led-strip-example2-trait-check = "check --example led_strip_example2_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led2d            = "run   --example led2d       --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led2d-check      = "check --example led2d       --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led2d-example1-trait = "run   --example led2d_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led2d-example1-trait-check = "check --example led2d_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led2d-example2-trait = "run   --example led2d_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led2d-example2-trait-check = "check --example led2d_example2_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
button-read      = "run   --example button_read --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
button-read-check = "check --example button_read --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
button-example1-trait = "run   --example button_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
button-example1-trait-check = "check --example button_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-example1-trait = "run   --example led_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led-example1-trait-check = "check --example led_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led-example1-trait-s3 = "run   --example led_example1_trait --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3"
led-example1-trait-check-s3 = "check --example led_example1_trait --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3"
char-lcd-simple = "run   --example char_lcd_simple --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
char-lcd-simple-check = "check --example char_lcd_simple --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
wifi-auto-force-button = "run   --example wifi_auto_force_button --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
wifi-auto-force-button-check = "check --example wifi_auto_force_button --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
wifi-auto-example1-trait = "run   --example wifi_auto_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
wifi-auto-example1-trait-check = "check --example wifi_auto_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
wifi-scan = "run   --example wifi_scan --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
wifi-scan-check = "check --example wifi_scan --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
wifi-dns-hex = "run   --example wifi_dns_hex --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
wifi-dns-hex-check = "check --example wifi_dns_hex --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-led8x12 = "run   --example clock_led8x12 --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-led8x12-check = "check --example clock_led8x12 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-led4 = "run   --example clock_led4 --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-led4-check = "check --example clock_led4 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-servos = "run   --example clock_servos --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-servos-check = "check --example clock_servos --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-sync-example1-trait = "run   --example clock_sync_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-sync-example1-trait-check = "check --example clock_sync_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-lcd = "run   --example clock_lcd --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-lcd-check = "check --example clock_lcd --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
clock-console-simple = "run   --example clock_console_simple --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
clock-console-simple-check = "check --release --example clock_console_simple --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
servo-basic = "run   --example servo_basic --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
servo-basic-check = "check --example servo_basic --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
servo-example1-trait = "run   --example servo_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
servo-example1-trait-check = "check --example servo_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
servo-example1-trait-s3 = "run   --example servo_example1_trait --target xtensa-esp32s3-none-elf --release --no-default-features --features esp32s3"
servo-example1-trait-check-s3 = "check --example servo_example1_trait --target xtensa-esp32s3-none-elf --no-default-features --features esp32s3"
servo-player-example1-trait = "run   --example servo_player_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
servo-player-example1-trait-check = "check --example servo_player_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
servo-player-example2-trait = "run   --example servo_player_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
servo-player-example2-trait-check = "check --example servo_player_example2_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
servos = "run   --example servos --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
servos-check = "check --example servos --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir = "run   --example ir --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-check = "check --example ir --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir-example1-trait = "run   --example ir_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-example1-trait-check = "check --example ir_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir-mapping-example1-trait = "run   --example ir_mapping_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-mapping-example1-trait-check = "check --example ir_mapping_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir-kepler-example1-trait = "run   --example ir_kepler_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-kepler-example1-trait-check = "check --example ir_kepler_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir-kepler = "run   --example ir_kepler --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-kepler-check = "check --example ir_kepler --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
ir-keplers = "run   --example ir_keplers --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
ir-keplers-check = "check --example ir_keplers --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
rfid = "run   --example rfid --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
rfid-check = "check --example rfid --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
conway = "run   --example conway --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
conway-check = "check --example conway --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led16x16test = "run   --example led16x16test --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led16x16test-check = "check --example led16x16test --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led16x16test-async = "run   --example led16x16test_async --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led16x16test-async-check = "check --example led16x16test_async --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led16x16-and-builtin = "run   --example led16x16_and_builtin --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led16x16-and-builtin-check = "check --example led16x16_and_builtin --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
led16x16-and-builtin-spi = "run   --example led16x16_and_builtin_spi --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
led16x16-and-builtin-spi-check = "check --example led16x16_and_builtin_spi --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
audio-example1 = "run   --example audio_example1 --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
audio-example1-check = "check --example audio_example1 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
audio-example1-trait = "run   --example audio_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
audio-example1-trait-check = "check --example audio_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
audio-example2-trait = "run   --example audio_example2_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
audio-example2-trait-check = "check --example audio_example2_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
audio-example3-trait = "run   --example audio_example3_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
audio-example3-trait-check = "check --example audio_example3_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
flash-block-example1-trait = "run   --example flash_block_example1_trait --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
flash-block-example1-trait-check = "check --example flash_block_example1_trait --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
audio = "run   --example audio --target riscv32imac-unknown-none-elf --release --no-default-features --features esp32c6"
audio-check = "check --example audio --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
