// @generated by cargo xtask generate-board-examples
//! Touch-triggered Wi-Fi/DNS reliability tester.
//!
//! Tap anywhere on the panel to fire one DNS query and update a running tally
//! of hits/misses and the last round-trip latency on a single status line.
//! Meant to run for hours unattended on hardware with no reachable physical
//! reset button, repeatedly exercising the touch driver and the Wi-Fi stack
//! together so long-run failures (socket exhaustion, dropped connections,
//! stuck touch reads) show up on screen instead of silently wedging the
//! board. The status line stays deliberately small: a full-screen frame
//! buffer plus the Wi-Fi stack's own heap overflows plain ESP32's DRAM.
//!
//! Wiring: a standalone 320x240 ILI9341 + XPT2046 module wired to spare
//! SPI-capable GPIOs (see `device_envoy_esp::cyd` module docs for the CYD
//! abstraction):
//!
//! - Display SPI SCK  -> GPIO1
//! - Display SPI MOSI -> GPIO2
//! - Display SPI MISO -> GPIO3
//! - Display CS       -> GPIO4
//! - Display DC       -> GPIO5
//! - Display RST      -> GPIO7
//! - Display backlight -> GPIO8
//! - Touch SPI SCK    -> GPIO9
//! - Touch SPI MOSI   -> GPIO10
//! - Touch SPI MISO   -> GPIO11
//! - Touch CS         -> GPIO12
//! - Touch IRQ        -> GPIO13
//! - Button (Wi-Fi reset while connecting; calibration backup afterward) -> GPIO6
//!   to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;
use embassy_net::dns::DnsQueryType;
use embassy_time::{Duration, Instant, Timer};
use embedded_graphics::{
    geometry::{Point, Size},
    primitives::Rectangle,
};
use esp_backtrace as _;
use log::{info, warn};

use device_envoy_core::cyd::touch::calibration::CalibrationConfig;
use device_envoy_core::cyd::touch::calibration::{CALIBRATION_MIN_PIXEL_COUNT, ensure_calibration};
use device_envoy_core::flash_block::FlashBlock as _;
use device_envoy_core::{
    cyd::display::Orientation,
    dns_tester::{DnsTesterUiError, DnsTesterUiNotice, DnsTesterUiState, render_notice},
};
use device_envoy_esp::{
    Error, Result,
    button::{Button as _, ButtonEsp, PressedTo},
    cyd::{
        CydDisplay as _, CydEsp, CydEspUncalibrated, CydStaticEsp, CydTouch as _,
        DEFAULT_DISPLAY_SPI_HZ, DEFAULT_FONT,
    },
    flash_block::FlashBlockEsp,
    init_and_start,
    wifi_auto::{WifiAuto as _, WifiAutoEsp, WifiAutoEvent},
};

esp_bootloader_esp_idf::esp_app_desc!();

const DNS_HOSTNAME: &str = "example.com";
const CAPTIVE_PORTAL_SSID: &str = "DeviceEnvoySetup";
const TOUCH_POLL_PERIOD: Duration = Duration::from_millis(16);

const CONTROL_HEIGHT: u32 = 20;

/// `ensure_calibration`'s own on-screen text banner needs a buffer at least
/// `CALIBRATION_MIN_PIXEL_COUNT` pixels; its crosshair/dot geometry streams
/// buffer-free. The DNS status line uses the same small-buffer budget.
const STATUS_PIXEL_COUNT: usize = CALIBRATION_MIN_PIXEL_COUNT;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD DNS tester on ESP32-S3 / esp32-s3-devkitc-1-v1.0-n16r8");

    let [
        wifi_auto_flash_block,
        mut calibration_flash_block,
        mut orientation_flash_block,
    ] = FlashBlockEsp::new_array::<3>(p.FLASH)?;
    let orientation = orientation_flash_block
        .load::<Orientation>()?
        .unwrap_or(Orientation::Landscape);
    let calibration_is_available = match calibration_flash_block.load::<CalibrationConfig>() {
        Ok(Some(_)) => true,
        Ok(None) | Err(_) => false,
    };
    let display_orientation = if calibration_is_available {
        orientation
    } else {
        // The shared calibration UI is always landscape. Apply a saved user
        // orientation only after calibration has already been completed.
        Orientation::Landscape
    };
    let mut button = ButtonEsp::new(p.GPIO6, PressedTo::Ground);

    static CYD_STATIC: CydStaticEsp<STATUS_PIXEL_COUNT> = CydEsp::new_static();
    let CydEspUncalibrated { mut display, touch } = CydEspUncalibrated::new(
        &CYD_STATIC,
        p.SPI2,
        p.GPIO1,
        p.GPIO2,
        p.GPIO3,
        p.GPIO4,
        p.GPIO5,
        p.GPIO7,
        p.GPIO8,
        DEFAULT_DISPLAY_SPI_HZ,
        display_orientation,
        embedded_graphics::pixelcolor::Rgb888::new(10, 10, 12), // near-black
        embedded_graphics::pixelcolor::Rgb888::new(230, 230, 230), // near-white
        &DEFAULT_FONT,
        p.SPI3,
        p.GPIO9,
        p.GPIO10,
        p.GPIO11,
        p.GPIO12,
        p.GPIO13,
    )?;
    info!("CYD display and touch initialized");

    let (mut touch, calibration_outcome) = ensure_calibration(
        &mut display,
        touch,
        &mut calibration_flash_block,
        &mut button,
        Some("recalibrating"),
    )
    .await?;
    if calibration_outcome.was_saved() {
        while button.is_pressed() {
            Timer::after(Duration::from_millis(10)).await;
        }
        info!("Calibration saved, restarting");
        device_envoy_esp::esp_hal::system::software_reset();
    }
    info!("Touch calibrated");

    render_dns_tester_notice(&mut display, orientation, DnsTesterUiNotice::WifiConnecting).await?;

    let wifi_auto = WifiAutoEsp::new(
        p.WIFI,
        wifi_auto_flash_block,
        CAPTIVE_PORTAL_SSID,
        [],
        spawner,
    )?;
    let stack = wifi_auto
        .connect(&mut button, async |wifi_auto_event| -> Result<(), Error> {
            let message = match wifi_auto_event {
                WifiAutoEvent::CaptivePortalReady => "WiFi setup: join DeviceEnvoySetup",
                WifiAutoEvent::Connecting { .. } => "Connecting to WiFi...",
                WifiAutoEvent::ConnectionFailed => "WiFi connect failed, retrying",
            };
            info!("Wi-Fi: {message}");
            Ok(())
        })
        .await?;

    while !stack.is_link_up() || stack.config_v4().is_none() {
        Timer::after(Duration::from_millis(200)).await;
    }
    info!("Wi-Fi up with DHCP: {:?}", stack.config_v4());

    let mut tap_count: u32 = 0;
    let mut success_count: u32 = 0;
    let mut failure_count: u32 = 0;
    let mut is_touch_down = false;

    render_dns_tester(
        &mut display,
        orientation,
        DnsTesterUiState {
            target: DNS_HOSTNAME,
            ..DnsTesterUiState::default()
        },
    )
    .await?;

    loop {
        if button.is_pressed() {
            while button.is_pressed() {
                Timer::after(Duration::from_millis(10)).await;
            }
            calibration_flash_block.clear()?;
            device_envoy_esp::esp_hal::system::software_reset();
        }
        if let Some(touch_event) = touch.read()? {
            match touch_event {
                device_envoy_esp::cyd::touch::TouchEvent::Down { point } => {
                    if !is_touch_down {
                        is_touch_down = true;
                        let point = orientation.map_landscape_point(point);
                        if let Some(control) = control_at(point, display.screen_size()) {
                            while !matches!(
                                touch.read()?,
                                Some(device_envoy_esp::cyd::touch::TouchEvent::Up)
                            ) {
                                Timer::after(TOUCH_POLL_PERIOD).await;
                            }
                            match control {
                                Control::Calibration => {
                                    calibration_flash_block.clear()?;
                                    device_envoy_esp::esp_hal::system::software_reset();
                                }
                                Control::Wifi => {
                                    wifi_auto.reset_to_captive_portal()?;
                                    device_envoy_esp::esp_hal::system::software_reset();
                                }
                                Control::Orientation => {
                                    orientation_flash_block.save(&orientation.next())?;
                                    device_envoy_esp::esp_hal::system::software_reset();
                                }
                            }
                        }
                        tap_count += 1;

                        let query_start = Instant::now();
                        let dns_result = stack.dns_query(DNS_HOSTNAME, DnsQueryType::A).await;
                        let last_latency_millis = query_start.elapsed().as_millis();

                        match dns_result {
                            Ok(addresses) if !addresses.is_empty() => {
                                success_count += 1;
                                info!("DNS ok in {last_latency_millis}ms: {:?}", addresses.first());
                            }
                            Ok(_) => {
                                failure_count += 1;
                                warn!("DNS query returned no addresses");
                            }
                            Err(_) => {
                                failure_count += 1;
                                warn!("DNS query failed");
                            }
                        }

                        render_dns_tester(
                            &mut display,
                            orientation,
                            DnsTesterUiState {
                                target: DNS_HOSTNAME,
                                queries: tap_count,
                                successes: success_count,
                                failures: failure_count,
                                last_latency_millis,
                            },
                        )
                        .await?;
                    }
                }
                device_envoy_esp::cyd::touch::TouchEvent::Move { .. } => {}
                device_envoy_esp::cyd::touch::TouchEvent::Up => {
                    is_touch_down = false;
                }
            }
        }
        Timer::after(TOUCH_POLL_PERIOD).await;
    }
}

async fn render_dns_tester(
    display: &mut device_envoy_esp::cyd::CydDisplayEsp,
    orientation: Orientation,
    state: DnsTesterUiState,
) -> Result<()> {
    device_envoy_core::dns_tester::render(display, orientation, state)
        .await
        .map_err(|error| match error {
            DnsTesterUiError::Text(_) => Error::FormatError,
            DnsTesterUiError::Display(error) => error.into(),
        })
}

async fn render_dns_tester_notice(
    display: &mut device_envoy_esp::cyd::CydDisplayEsp,
    orientation: Orientation,
    notice: DnsTesterUiNotice,
) -> Result<()> {
    render_notice(display, orientation, notice)
        .await
        .map_err(|error| match error {
            DnsTesterUiError::Text(_) => Error::FormatError,
            DnsTesterUiError::Display(error) => error.into(),
        })
}

#[derive(Clone, Copy)]
enum Control {
    Orientation,
    Calibration,
    Wifi,
}

fn control_at(point: Point, screen_size: Size) -> Option<Control> {
    [Control::Orientation, Control::Wifi, Control::Calibration]
        .into_iter()
        .find(|control| {
            let index = match control {
                Control::Orientation => 0,
                Control::Wifi => 1,
                Control::Calibration => 2,
            };
            Rectangle::new(
                Point::new(
                    screen_size.width as i32 - screen_size.width as i32 / 3 * (3 - index),
                    screen_size.height as i32 - CONTROL_HEIGHT as i32,
                ),
                Size::new(screen_size.width / 3, CONTROL_HEIGHT),
            )
            .contains(point)
        })
}
