// @generated by cargo xtask generate-board-examples
//!
//! Wiring:
//! - Follow the board-specific pin mapping shown in this file.
#![allow(missing_docs)]
#![no_std]
#![no_main]

use core::convert::Infallible;

use core::time::Duration as StdDuration;

use embassy_executor::Spawner;
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start};

use device_envoy_esp::{
    audio_player::AtEnd, audio_player::AudioPlayer as _, audio_player::SilenceClip,
    audio_player::VOICE_22050_HZ, audio_player::Volume, audio_player::audio_player, tone,
};

esp_bootloader_esp_idf::esp_app_desc!();

audio_player! {
    AudioPlayerBoard {
        data_pin: GPIO21,
        bit_clock_pin: GPIO3,
        word_select_pin: GPIO4,
        sample_rate_hz: VOICE_22050_HZ,
        dma: DMA_CH0,
        max_volume: Volume::percent(25),
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);

    const REST: &AudioPlayerBoardPlayable = &SilenceClip::new(StdDuration::from_millis(80));
    const SAMPLE_RATE_HZ: u32 = AudioPlayerBoard::SAMPLE_RATE_HZ;
    const NOTE_DURATION: StdDuration = StdDuration::from_millis(220);
    const NOTE_E4: &AudioPlayerBoardPlayable = &tone!(330, SAMPLE_RATE_HZ, NOTE_DURATION);
    const NOTE_D4: &AudioPlayerBoardPlayable = &tone!(294, SAMPLE_RATE_HZ, NOTE_DURATION);
    const NOTE_C4: &AudioPlayerBoardPlayable = &tone!(262, SAMPLE_RATE_HZ, NOTE_DURATION);

    let audio_player_board =
        AudioPlayerBoard::new(p.GPIO21, p.GPIO3, p.GPIO4, p.I2S0, p.DMA_CH0, spawner)?;
    audio_player_board.play(
        [
            NOTE_E4, REST, NOTE_D4, REST, NOTE_C4, REST, NOTE_D4, REST, NOTE_E4, REST, NOTE_E4,
            REST, NOTE_E4,
        ],
        AtEnd::Stop,
    );

    core::future::pending().await
}
