// @generated by cargo xtask generate-board-examples
#![allow(missing_docs)]
//! MAX98357A sample playback example using ESP32-C6 I2S.
//!
//! Wiring:
//! - Data pin (`DIN`) -> GPIO21
//! - Bit clock pin (`BCLK`) -> GPIO3
//! - Word select pin (`LRC` / `LRCLK`) -> GPIO4
//! - Button -> GPIO6 to GND (starts playback)

#![no_std]
#![no_main]

use core::convert::Infallible;

use core::time::Duration as StdDuration;

use embassy_executor::Spawner;

use embassy_time::{Duration, Timer};

use esp_backtrace as _;
use log::info;

use device_envoy_esp::{Result, init_and_start};

use device_envoy_esp::{
    audio_player::{
        AtEnd, AudioPlayer, Gain, SilenceClip, VOICE_22050_HZ, Volume, audio_player, pcm_clip,
    },
    button::{Button as _, ButtonEsp, PressedTo},
    tone,
};

esp_bootloader_esp_idf::esp_app_desc!();

audio_player! {
    AudioPlayerBoard {
        data_pin: GPIO21,
        bit_clock_pin: GPIO3,
        word_select_pin: GPIO4,
        sample_rate_hz: VOICE_22050_HZ,
        dma: DMA_CH0,
        max_volume: Volume::percent(50),
        initial_volume: Volume::percent(100),
    }
}

pcm_clip! {
    Nasa {
        file: concat!(env!("CARGO_MANIFEST_DIR"), "/examples/data/audio/nasa_22k.s16"),
        source_sample_rate_hz: VOICE_22050_HZ,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);

    const NASA: &AudioPlayerBoardPlayable = &Nasa::pcm_clip().with_gain(Gain::percent(25));
    const TONE_A4: &AudioPlayerBoardPlayable = &tone!(
        440,
        AudioPlayerBoard::SAMPLE_RATE_HZ,
        StdDuration::from_millis(500)
    )
    .with_gain(Gain::percent(25));
    const SILENCE_100MS: &AudioPlayerBoardPlayable =
        &SilenceClip::new(StdDuration::from_millis(100));

    let mut button = ButtonEsp::new(p.GPIO6, PressedTo::Ground);

    let audio_player_board =
        AudioPlayerBoard::new(p.GPIO21, p.GPIO3, p.GPIO4, p.I2S0, p.DMA_CH0, spawner)?;

    info!("I2S ready: GPIO21 DIN, GPIO3 BCLK, GPIO4 LRCLK");
    info!(
        "Loaded sample: {} samples ({} bytes), 22.05kHz mono s16le",
        Nasa::PCM_SAMPLE_COUNT,
        Nasa::PCM_SAMPLE_COUNT * 2
    );
    info!("Button on GPIO6 starts playback");

    loop {
        button.wait_for_press().await;
        audio_player_board.play([TONE_A4, SILENCE_100MS, TONE_A4], AtEnd::Loop);
        info!("Started static slice playback");
        for percent in [80, 60, 40, 20, 200] {
            audio_player_board.set_volume(Volume::percent(percent));
            info!("Runtime volume set to {}%", percent);
            Timer::after(Duration::from_secs(1)).await;
        }
        audio_player_board.stop();
        Timer::after(Duration::from_secs(1)).await;
        audio_player_board.set_volume(
            <AudioPlayerBoard as AudioPlayer<{ AudioPlayerBoard::SAMPLE_RATE_HZ }>>::INITIAL_VOLUME,
        );
        audio_player_board.play([NASA], AtEnd::Stop);
    }
}
