// @generated by `cargo xtask generate-board-examples`. Do not edit by hand.
//! Shared RMT blocking demo for `generic` (ESP32-C6): drive a 16x16 panel and one NeoPixel-style (WS2812) LED independently.
//!
//! Wiring:
//! - GPIO2: 16x16 NeoPixel-style (WS2812) panel data-in
//! - GPIO8: external NeoPixel-style (WS2812) LED data-in

#![no_std]
#![no_main]

use core::convert::Infallible;
use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{
    init_and_start, led2d,
    led2d::{layout::LedLayout, Frame2d, Led2d, Led2dFont},
    led_strip,
    led_strip::{colors, Current, Frame1d, LedStrip as _},
    Result,
};

esp_bootloader_esp_idf::esp_app_desc!();

#[cfg(all(not(rust_analyzer), not(feature = "esp32c6")))]
compile_error!("This board example only supports --features esp32c6.");

const PANEL_16X16_PIN_NUM: u8 = 2;
const LED_STRIP1_PIN_NUM: u8 = 8;
const LED_LAYOUT_16X16: LedLayout<256, 16, 16> = LedLayout::serpentine_column_major();

led2d! {
    Led16x16Dual {
        pin: GPIO2,
        len: 256,
        led_layout: LED_LAYOUT_16X16,
        max_current: Current::Milliamps(700),
        font: Led2dFont::Font4x6Trim,
        max_frames: 4,
    }
}

led_strip! {
    LedStrip1 {
        pin: GPIO8,
        len: 1,
        max_current: Current::Milliamps(10),
        max_frames: 4,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Blocking);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!(
        "led16x16_plus_1: panel on GPIO{}, strip1 LED on GPIO{} (generic)",
        PANEL_16X16_PIN_NUM, LED_STRIP1_PIN_NUM
    );

    let led16x16_dual = Led16x16Dual::new(p.GPIO2, rmt80.channel0, spawner)?;
    let led_strip1 = LedStrip1::new(p.GPIO8, rmt80.channel1, spawner)?;

    let mut panel_x_index = 0usize;
    let mut panel_y_index = 0usize;
    let mut led_strip1_on = false;
    let mut tick_index = 0usize;
    const TICK: Duration = Duration::from_millis(120);

    loop {
        let strip1_frame = if led_strip1_on {
            Frame1d([colors::MAGENTA])
        } else {
            Frame1d([colors::BLACK])
        };
        led_strip1.write_frame(strip1_frame);
        led_strip1_on = !led_strip1_on;

        if tick_index % 2 == 0 {
            let mut panel_frame2d = Frame2d::<16, 16>::new();
            panel_frame2d[(panel_x_index, panel_y_index)] = colors::WHITE;
            Led2d::write_frame(&led16x16_dual, panel_frame2d);
            panel_x_index += 1;
            if panel_x_index >= 16 {
                panel_x_index = 0;
                panel_y_index = (panel_y_index + 1) % 16;
            }
        }

        tick_index = tick_index.wrapping_add(1);
        Timer::after(TICK).await;
    }
}