// @generated by cargo xtask generate-board-examples
//! Calibrates the touch panel once (persisting the result to flash) and then
//! paints a small filled circle at every touch point — a minimal interactive
//! demo of `device_envoy_esp::cyd`'s calibration flow and calibrated touch
//! event stream.
//!
//! Wiring: a standalone 320x240 ILI9341 + XPT2046 module wired to spare
//! SPI-capable GPIOs (see `device_envoy_esp::cyd` module docs for the CYD
//! abstraction):
//!
//! - Display SPI SCK  -> GPIO1
//! - Display SPI MOSI -> GPIO2
//! - Display SPI MISO -> GPIO3
//! - Display CS       -> GPIO4
//! - Display DC       -> GPIO5
//! - Display RST      -> GPIO7
//! - Display backlight -> GPIO8
//! - Touch SPI SCK    -> GPIO9
//! - Touch SPI MOSI   -> GPIO10
//! - Touch SPI MISO   -> GPIO11
//! - Touch CS         -> GPIO12
//! - Touch IRQ        -> GPIO13
//! - Recalibration button -> GPIO6 to GND (`PressedTo::Ground`)
//! - Plus 3.3V and GND
#![no_std]
#![no_main]

use core::convert::Infallible;

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use embedded_graphics::{
    Drawable,
    pixelcolor::{Rgb565, Rgb888},
    prelude::Point,
    primitives::{Circle, Primitive, PrimitiveStyle},
};
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{
    Result,
    button::{ButtonEsp, PressedTo},
    cyd::{
        Cyd, CydDisplay as _, CydEsp, CydStaticEsp, CydTouch as _, DEFAULT_DISPLAY_SPI_HZ,
        DEFAULT_FONT, Orientation,
    },
    flash_block::FlashBlockEsp,
    init_and_start,
};

esp_bootloader_esp_idf::esp_app_desc!();

const TOUCH_DOT_RADIUS: u32 = 5;

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(_spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("Starting CYD touch-paint demo");

    let [mut calibration_flash_block] = FlashBlockEsp::new_array::<1>(p.FLASH)?;
    let mut recalibration_button = ButtonEsp::new(p.GPIO6, PressedTo::Ground);

    static CYD_STATIC: CydStaticEsp<{ CydEsp::SCREEN_PIXELS }> = CydEsp::new_static();
    let mut cyd = CydEsp::new(
        &CYD_STATIC,
        p.SPI2,
        p.GPIO1,
        p.GPIO2,
        p.GPIO3,
        p.GPIO4,
        p.GPIO5,
        p.GPIO7,
        p.GPIO8,
        DEFAULT_DISPLAY_SPI_HZ,
        Orientation::Landscape,
        Rgb888::new(10, 10, 12),
        Rgb888::new(230, 230, 230),
        &DEFAULT_FONT,
        p.SPI3,
        p.GPIO9,
        p.GPIO10,
        p.GPIO11,
        p.GPIO12,
        p.GPIO13,
        &mut calibration_flash_block,
        &mut recalibration_button,
    )
    .await?;
    info!("CYD display and touch initialized");
    info!("Touch calibrated; tap the panel to paint");

    let (display, touch) = cyd.parts();
    display.full_frame_mut().flush()?;

    loop {
        if let Some(touch_event) = touch.try_read()? {
            let point = match touch_event {
                device_envoy_esp::cyd::touch::TouchEvent::Down { point }
                | device_envoy_esp::cyd::touch::TouchEvent::Move { point } => Some(point),
                device_envoy_esp::cyd::touch::TouchEvent::Up => None,
            };
            if let Some(point) = point {
                let mut frame = display.full_frame_mut();
                Circle::with_center(Point::new(point.x, point.y), TOUCH_DOT_RADIUS * 2)
                    .into_styled(PrimitiveStyle::with_fill(Rgb565::new(28, 50, 12)))
                    .draw(&mut frame)
                    .expect("drawing onto an Infallible CYD frame cannot fail");
                frame.flush()?;
            }
        }
        Timer::after(Duration::from_millis(16)).await;
    }
}
