// @generated by `cargo xtask generate-board-examples`
//! Mixed backend demo for `esp32-s3-devkitc-1-v1.1-n16r8` (ESP32-S3): 16x16 panel via SPI and one NeoPixel-style (WS2812) LED via RMT.
//!
//! Wiring:
//! - GPIO2: 16x16 NeoPixel-style (WS2812) panel data-in (SPI MOSI)
//! - GPIO38: built-in NeoPixel-style (WS2812) LED (RMT)

#![no_std]
#![no_main]

use core::convert::Infallible;
use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_backtrace as _;
use log::info;

#[allow(unused_imports)]
use device_envoy_esp::led_strip::Engine;
use device_envoy_esp::{
    Result, init_and_start, led_strip,
    led_strip::{Current, Frame1d, LedStrip as _, colors},
    led2d,
    led2d::{Frame2d, Led2d, Led2dFont, layout::LedLayout},
};

esp_bootloader_esp_idf::esp_app_desc!();

const LED_LAYOUT_16X16: LedLayout<256, 16, 16> = LedLayout::serpentine_column_major();

led2d! {
    Led16x16DualSpi {
        pin: GPIO2,
        len: 256,
        led_layout: LED_LAYOUT_16X16,
        max_current: Current::Milliamps(700),
        font: Led2dFont::Font4x6Trim,
        engine: Engine::Spi,
        max_frames: 4,
    }
}

led_strip! {
    LedStrip1Rmt {
        pin: GPIO38,
        len: 1,
        max_current: Current::Milliamps(10),
        max_frames: 4,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p, rmt80: rmt80, mode: rmt_mode::Blocking);
    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!(
        "led16x16_plus_1_spi: panel on GPIO2 via SPI2, strip1 LED on GPIO38 via RMT (esp32-s3-devkitc-1-v1.1-n16r8)"
    );

    let led16x16_dual_spi = Led16x16DualSpi::new(p.GPIO2, p.SPI2, spawner)?;
    let led_strip1_rmt = LedStrip1Rmt::new(p.GPIO38, rmt80.channel1, spawner)?;

    let mut panel_x_index = 0usize;
    let mut panel_y_index = 0usize;
    let mut led_strip1_on = false;
    let mut tick_index = 0usize;
    const TICK: Duration = Duration::from_millis(120);

    loop {
        let strip1_frame = if led_strip1_on {
            Frame1d([colors::MAGENTA])
        } else {
            Frame1d([colors::BLACK])
        };
        led_strip1_rmt.write_frame(strip1_frame);
        led_strip1_on = !led_strip1_on;

        if tick_index % 2 == 0 {
            let mut panel_frame2d = Frame2d::<16, 16>::new();
            panel_frame2d[(panel_x_index, panel_y_index)] = colors::WHITE;
            Led2d::write_frame(&led16x16_dual_spi, panel_frame2d);
            panel_x_index += 1;
            if panel_x_index >= 16 {
                panel_x_index = 0;
                panel_y_index = (panel_y_index + 1) % 16;
            }
        }

        tick_index = tick_index.wrapping_add(1);
        Timer::after(TICK).await;
    }
}
